namespace offsets
{
	namespace AAirDropTreasureBox
	{
			constexpr auto bPendingDestroy = 0x5d0; // Size: 1, Type: bool
			constexpr auto bIsOpening = 0x5d1; // Size: 1, Type: bool
			constexpr auto openProgress = 0x5d4; // Size: 4, Type: float
			constexpr auto OpeningCharacter = 0x5d8; // Size: 8, Type: struct ASolarCharacter*
			constexpr auto OpenTime = 0x5e0; // Size: 4, Type: float
			constexpr auto ProtectionTime = 0x5e4; // Size: 4, Type: float
			constexpr auto bBoxLanded = 0x5f5; // Size: 1, Type: bool
			constexpr auto SummonPlayerID = 0x650; // Size: 16, Type: struct FString
			constexpr auto StartDropHeight = 0x660; // Size: 4, Type: float
			constexpr auto TargetRotation = 0x664; // Size: 12, Type: struct FRotator
			constexpr auto TargetLocation = 0x670; // Size: 12, Type: struct FVector
			constexpr auto OpenAirdropEffect = 0x680; // Size: 40, Type: struct TSoftObjectPtr<UParticleSystem>
			constexpr auto LandHitEffect = 0x6a8; // Size: 40, Type: struct TSoftObjectPtr<UParticleSystem>
			constexpr auto LandSmokeEffect = 0x6d0; // Size: 40, Type: struct TSoftObjectPtr<UParticleSystem>
			constexpr auto PendingDestroyEffect = 0x6f8; // Size: 40, Type: struct TSoftObjectPtr<UParticleSystem>
			constexpr auto DestroyEffect = 0x720; // Size: 40, Type: struct TSoftObjectPtr<UParticleSystem>
			constexpr auto FallingEffect = 0x748; // Size: 40, Type: struct TSoftObjectPtr<UParticleSystem>
			constexpr auto FallingImpulseEffect = 0x770; // Size: 40, Type: struct TSoftObjectPtr<UParticleSystem>
			constexpr auto LightBeamEffect = 0x798; // Size: 40, Type: struct TSoftObjectPtr<UParticleSystem>
			constexpr auto FallingEffectOffset = 0x7c0; // Size: 48, Type: struct FTransform
			constexpr auto FallingImpulseEffectOffset = 0x7f0; // Size: 48, Type: struct FTransform
			constexpr auto LightBeamEffectOffset = 0x820; // Size: 48, Type: struct FTransform
			constexpr auto PendingDestroyEffectOffset = 0x850; // Size: 48, Type: struct FTransform
			constexpr auto LandAnimation = 0x880; // Size: 8, Type: struct UAnimationAsset*
			constexpr auto OpenAnimation = 0x888; // Size: 8, Type: struct UAnimationAsset*
			constexpr auto dropGravity = 0x890; // Size: 4, Type: float
			constexpr auto maxDropSpeed = 0x894; // Size: 4, Type: float
			constexpr auto originHeight = 0x898; // Size: 4, Type: float
			constexpr auto DecelerateHeight = 0x89c; // Size: 4, Type: float
			constexpr auto ShowLandSmokeHeight = 0x8a0; // Size: 4, Type: float
			constexpr auto DecelerateTime = 0x8a4; // Size: 4, Type: float
			constexpr auto DecelerateCurve = 0x8a8; // Size: 8, Type: struct UCurveFloat*
			constexpr auto AirDropSpawnDelay = 0x8b0; // Size: 4, Type: float
			constexpr auto AudioActorHeightOffset = 0x8b4; // Size: 4, Type: float
			constexpr auto AudioActorFallSpeed = 0x8b8; // Size: 4, Type: float
			constexpr auto AirDropGuideMeshBPClassPath = 0x8c0; // Size: 24, Type: struct FSoftClassPath
			constexpr auto DropApprochDuration = 0x8d8; // Size: 4, Type: float
			constexpr auto FallingEffectDelay = 0x8dc; // Size: 4, Type: float
			constexpr auto bSummonBySkill = 0x8e0; // Size: 1, Type: bool
			constexpr auto YawOffset = 0x8e4; // Size: 4, Type: float
			constexpr auto MovementState = 0x8e8; // Size: 1, Type: enum class EAirDropMovementState
			constexpr auto OpenState = 0x8e9; // Size: 1, Type: enum class EAirDropOpenState
			constexpr auto SkeletalMeshComp = 0x8f0; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto FallingPSC = 0x948; // Size: 8, Type: struct UParticleSystemComponent*
			constexpr auto DamageInfo = 0x968; // Size: 64, Type: struct FSolarDamageInfo
			constexpr auto SNameAirDropOpen = 0x9a8; // Size: 16, Type: struct FString
			constexpr auto SNameLandHit = 0x9b8; // Size: 16, Type: struct FString
			constexpr auto SNameAirDropSpawn = 0x9c8; // Size: 16, Type: struct FString
			constexpr auto SNameAirDropSpawnWarning = 0x9d8; // Size: 16, Type: struct FString
			constexpr auto SNameAirDropStopSpawnWarning = 0x9e8; // Size: 16, Type: struct FString
			constexpr auto SNameAirDropApprochWarning = 0x9f8; // Size: 16, Type: struct FString
			constexpr auto SNameAirDropStopApprochWarning = 0xa08; // Size: 16, Type: struct FString
			constexpr auto SNameStartDrop = 0xa18; // Size: 16, Type: struct FString
			constexpr auto SNameStopDrop = 0xa28; // Size: 16, Type: struct FString
			constexpr auto SNameDecelerateAudio = 0xa38; // Size: 16, Type: struct FString
			constexpr auto SNamePlayLandedLoopAudio = 0xa48; // Size: 16, Type: struct FString
			constexpr auto SNameStopLandedLoopAudio = 0xa58; // Size: 16, Type: struct FString
			constexpr auto SNamePlayOnGroundBroadcastLoopAudio = 0xa68; // Size: 16, Type: struct FString
			constexpr auto SNameStopOnGroundBroadcastLoopAudio = 0xa78; // Size: 16, Type: struct FString
			constexpr auto SNamePlayStartHackAudio = 0xa88; // Size: 16, Type: struct FString
			constexpr auto SNameStopStartHackAudio = 0xa98; // Size: 16, Type: struct FString
			constexpr auto SNamePlayHackingLoopAudio = 0xaa8; // Size: 16, Type: struct FString
			constexpr auto SNameStopHackingLoopAudio = 0xab8; // Size: 16, Type: struct FString
			constexpr auto SNameStopHackingLoopAudioAux = 0xac8; // Size: 16, Type: struct FString
			constexpr auto PendingDestroyLoopStart = 0xad8; // Size: 16, Type: struct FString
			constexpr auto PendingDestroyLoopEnd = 0xae8; // Size: 16, Type: struct FString
			constexpr auto SNameDestroySound = 0xaf8; // Size: 16, Type: struct FString
			constexpr auto ColorKeyTag1 = 0xb70; // Size: 8, Type: struct FName
			constexpr auto ColorKeyTag2 = 0xb78; // Size: 8, Type: struct FName
			constexpr auto ColorKeyGlow = 0xb80; // Size: 8, Type: struct FName
			constexpr auto ColorKeyMesh = 0xb88; // Size: 8, Type: struct FName
			constexpr auto AlphaKey = 0xb90; // Size: 8, Type: struct FName
			constexpr auto LightBeamAlphaKey = 0xb98; // Size: 8, Type: struct FName
			constexpr auto ColorKeyTagFlow1 = 0xba0; // Size: 8, Type: struct FName
			constexpr auto ColorKeyTagFlow2 = 0xba8; // Size: 8, Type: struct FName
			constexpr auto ColorKeyLightEffect = 0xbb0; // Size: 8, Type: struct FName
			constexpr auto FadeTweenDuration = 0xbb8; // Size: 4, Type: float
			constexpr auto RedTweenDuration = 0xbbc; // Size: 4, Type: float
			constexpr auto BlueColorTag1 = 0xbc0; // Size: 16, Type: struct FLinearColor
			constexpr auto RedColorTag1 = 0xbd0; // Size: 16, Type: struct FLinearColor
			constexpr auto BlueColorTag2 = 0xbe0; // Size: 16, Type: struct FLinearColor
			constexpr auto RedColorTag2 = 0xbf0; // Size: 16, Type: struct FLinearColor
			constexpr auto BlueColorGlow = 0xc00; // Size: 16, Type: struct FLinearColor
			constexpr auto RedColorGlow = 0xc10; // Size: 16, Type: struct FLinearColor
			constexpr auto BlueColorMesh = 0xc20; // Size: 16, Type: struct FLinearColor
			constexpr auto RedColorMesh = 0xc30; // Size: 16, Type: struct FLinearColor
			constexpr auto RedColorTagFlow1 = 0xc40; // Size: 16, Type: struct FLinearColor
			constexpr auto RedColorTagFlow2 = 0xc50; // Size: 16, Type: struct FLinearColor
			constexpr auto BlueColorTagFlow1 = 0xc60; // Size: 16, Type: struct FLinearColor
			constexpr auto BlueColorTagFlow2 = 0xc70; // Size: 16, Type: struct FLinearColor
			constexpr auto RedColorLightEffect = 0xc80; // Size: 16, Type: struct FLinearColor
			constexpr auto BlueColorLightEffect = 0xc90; // Size: 16, Type: struct FLinearColor
	}
} 
