namespace offsets
{
	namespace ASolarPlayerState
	{
			constexpr auto OnTeammatePlayerStateRepDelegate = 0x330; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnTeammatePlayerStateRemovedInPreparatoryPhaseDelegate = 0x340; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnTeammatePlayerStateRemovedInBattlePhaseDelegate = 0x350; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnPlayerChangedGoldsDelegate = 0x360; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnOBPlayerRepDelegate = 0x370; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto Gold = 0x380; // Size: 4, Type: int32_t
			constexpr auto CostedGolds = 0x388; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto ReceivedGolds = 0x398; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto CharacterId = 0x3a8; // Size: 4, Type: int32_t
			constexpr auto SkinId = 0x3ac; // Size: 4, Type: int32_t
			constexpr auto ClanId = 0x3b0; // Size: 16, Type: struct FString
			constexpr auto ClanName = 0x3c0; // Size: 16, Type: struct FString
			constexpr auto ClanShortName = 0x3d0; // Size: 16, Type: struct FString
			constexpr auto BagId = 0x3e0; // Size: 4, Type: int32_t
			constexpr auto CapsuleID = 0x3e4; // Size: 4, Type: int32_t
			constexpr auto SolarPlayerID = 0x3e8; // Size: 16, Type: struct FString
			constexpr auto NickName = 0x3f8; // Size: 16, Type: struct FString
			constexpr auto BattleVoiceId = 0x408; // Size: 4, Type: uint32_t
			constexpr auto RTCType = 0x410; // Size: 8, Type: int64_t
			constexpr auto UserId = 0x418; // Size: 8, Type: uint64_t
			constexpr auto PosInTeam = 0x420; // Size: 1, Type: char
			constexpr auto Side = 0x428; // Size: 16, Type: struct FString
			constexpr auto Job = 0x438; // Size: 16, Type: struct FString
			constexpr auto CharacterLevel = 0x448; // Size: 4, Type: int32_t
			constexpr auto AvatarID = 0x44c; // Size: 4, Type: int32_t
			constexpr auto AvatarFrameID = 0x450; // Size: 4, Type: int32_t
			constexpr auto Gender = 0x454; // Size: 4, Type: int32_t
			constexpr auto AccountLevel = 0x458; // Size: 4, Type: int32_t
			constexpr auto FriendNum = 0x45c; // Size: 4, Type: int32_t
			constexpr auto RoleID = 0x460; // Size: 4, Type: int32_t
			constexpr auto Medals = 0x468; // Size: 16, Type: struct TArray<struct FMedalInfo>
			constexpr auto AllCharacterData = 0x478; // Size: 16, Type: struct TArray<struct FBattleCharacterData>
			constexpr auto CurUsedCharacterData = 0x488; // Size: 72, Type: struct FBattleCharacterData
			constexpr auto AllExpRankMedalData = 0x4d0; // Size: 16, Type: struct TArray<struct FExpRankMedalData>
			constexpr auto LastBattleInfo = 0x4e0; // Size: 28, Type: struct FLastBattleInfo
			constexpr auto RoleUltimateSkillCDState = 0x4fc; // Size: 4, Type: int32_t
			constexpr auto ExtraRewards = 0x500; // Size: 16, Type: struct TArray<struct FSettlementParam_ExtraRewardInfo>
			constexpr auto SettlementRewards = 0x510; // Size: 16, Type: struct TArray<struct FSettlementReward>
			constexpr auto CrateRewards = 0x520; // Size: 16, Type: struct TArray<struct FSettlementCrateReward>
			constexpr auto PlayerNumber = 0x530; // Size: 4, Type: uint32_t
			constexpr auto VehicleSkinData = 0x538; // Size: 80, Type: struct TMap<int32_t, int32_t>
			constexpr auto CurrentHealth = 0x588; // Size: 4, Type: float
			constexpr auto MaxHealth = 0x58c; // Size: 4, Type: float
			constexpr auto CurShieldInfo = 0x590; // Size: 8, Type: struct FShieldInfo
			constexpr auto ReviveItemNum = 0x598; // Size: 1, Type: char
			constexpr auto ReviveCountByItem = 0x599; // Size: 1, Type: char
			constexpr auto TalentID = 0x59c; // Size: 4, Type: int32_t
			constexpr auto LikeValue = 0x5a0; // Size: 4, Type: int32_t
			constexpr auto ReceivedGiftNum = 0x5a4; // Size: 4, Type: int32_t
			constexpr auto SpectatorNum = 0x5a8; // Size: 4, Type: int32_t
			constexpr auto TalentState = 0x5ac; // Size: 1, Type: enum class ETalentState
			constexpr auto HasBackendVerified = 0x5ad; // Size: 1, Type: bool
			constexpr auto HasGroupBackendVerified = 0x5ae; // Size: 1, Type: bool
			constexpr auto MarkedPointInNavMap = 0x5b0; // Size: 8, Type: struct FVector2D
			constexpr auto SelfLastVehicleLocation = 0x5b8; // Size: 12, Type: struct FVector
			constexpr auto TeamLastVehicleLocation = 0x5c4; // Size: 12, Type: struct FVector
			constexpr auto CurrentPlayerStateInGame = 0x5d0; // Size: 1, Type: char
			constexpr auto CurrentCharacterStateInGame = 0x5d1; // Size: 1, Type: char
			constexpr auto AccountFlag = 0x628; // Size: 4, Type: int32_t
			constexpr auto ClanFlag = 0x62c; // Size: 4, Type: int32_t
			constexpr auto EquippedEmotes = 0x630; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto OS = 0x640; // Size: 16, Type: struct FString
			constexpr auto OsType = 0x650; // Size: 16, Type: struct FString
			constexpr auto DeviceModel = 0x660; // Size: 16, Type: struct FString
			constexpr auto InputType = 0x670; // Size: 1, Type: enum class ECommonInputType
			constexpr auto bIsSameTeamWithLocalPlayer = 0x671; // Size: 1, Type: bool
			constexpr auto HasReconnection = 0x672; // Size: 1, Type: bool
			constexpr auto bHasHangUpBehavior = 0x678; // Size: 1, Type: bool
			constexpr auto HangUpTime = 0x67c; // Size: 4, Type: float
			constexpr auto OfflineBattleTime = 0x680; // Size: 4, Type: float
			constexpr auto Elo = 0x684; // Size: 4, Type: int32_t
			constexpr auto RankLevel = 0x688; // Size: 4, Type: int32_t
			constexpr auto RankLevel2 = 0x68c; // Size: 4, Type: int32_t
			constexpr auto LegendRank = 0x690; // Size: 4, Type: int32_t
			constexpr auto VipType = 0x694; // Size: 1, Type: char
			constexpr auto WarmupTag = 0x698; // Size: 4, Type: int32_t
			constexpr auto Frustration = 0x69c; // Size: 4, Type: float
			constexpr auto bMonitor = 0x6a0; // Size: 1, Type: bool
			constexpr auto LobbyTeamMemberNum = 0x6a1; // Size: 1, Type: char
			constexpr auto bTeamIDHasChanged = 0x6b8; // Size: 1, Type: bool
			constexpr auto RepliableMessageID = 0x6bc; // Size: 4, Type: int32_t
			constexpr auto RepliableMessageStartTime = 0x6c0; // Size: 4, Type: float
			constexpr auto bIsOBPlayer = 0x6d0; // Size: 1, Type: bool
			constexpr auto WarmId = 0x6d4; // Size: 4, Type: int32_t
			constexpr auto WarmType = 0x6d8; // Size: 4, Type: int32_t
			constexpr auto AllowOtherJoin = 0x6dc; // Size: 1, Type: bool
			constexpr auto WaitTimeBeforeEnterSpectateMode = 0x6e0; // Size: 4, Type: float
			constexpr auto OnSpectateInfoRep = 0x6e8; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto KillerPlayerState = 0x6f8; // Size: 8, Type: struct ASolarPlayerState*
			constexpr auto RevengePlayerState = 0x700; // Size: 8, Type: struct ASolarPlayerState*
			constexpr auto KilledEnemysRecord = 0x708; // Size: 16, Type: struct TArray<struct FKillEnemySnapshot>
			constexpr auto SpectateInfo = 0x718; // Size: 8, Type: struct ASolarSpectateInfo*
			constexpr auto NetStateInGame = 0x720; // Size: 1, Type: enum class EPlayerNetStateInGame
			constexpr auto bHasLogin = 0x721; // Size: 1, Type: bool
			constexpr auto bHasUpdateByServerData = 0x730; // Size: 1, Type: bool
			constexpr auto ReplayHightlightComp = 0x738; // Size: 8, Type: struct USolarReplayHighlightComponent*
			constexpr auto KillNum = 0x740; // Size: 4, Type: int32_t
			constexpr auto AssistNum = 0x760; // Size: 4, Type: int32_t
			constexpr auto DeathPos = 0x780; // Size: 12, Type: struct FVector
			constexpr auto ReconnectNum = 0x78c; // Size: 4, Type: int32_t
			constexpr auto MultiKillDurationTime = 0x7a0; // Size: 4, Type: float
			constexpr auto TotalReceivedDamage = 0x7b8; // Size: 4, Type: float
			constexpr auto HealSelf = 0x7bc; // Size: 4, Type: float
			constexpr auto ReceivedHeal = 0x7c0; // Size: 4, Type: float
			constexpr auto LifeTime = 0x7c4; // Size: 4, Type: float
			constexpr auto SettleSyncData = 0x7c8; // Size: 216, Type: struct FSettlementTempData
			constexpr auto PlayerRank = 0x8a0; // Size: 4, Type: int32_t
			constexpr auto IsAce = 0x8a4; // Size: 1, Type: bool
			constexpr auto bMVP = 0x8a5; // Size: 1, Type: bool
			constexpr auto IsVictory = 0x8a7; // Size: 1, Type: bool
			constexpr auto MvpScore = 0x8a8; // Size: 4, Type: float
			constexpr auto KDA = 0x8ac; // Size: 4, Type: float
			constexpr auto ResurrectionTimes = 0x8b0; // Size: 4, Type: int32_t
			constexpr auto CharacterExp = 0x8b4; // Size: 4, Type: int32_t
			constexpr auto CharacterExpReason = 0x8b8; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto GainCombatScore = 0x8c8; // Size: 4, Type: int32_t
			constexpr auto AccountExp = 0x8cc; // Size: 4, Type: int32_t
			constexpr auto WeaponExps = 0x8d0; // Size: 80, Type: struct TMap<int32_t, int32_t>
			constexpr auto Zomborg = 0x920; // Size: 4, Type: int32_t
			constexpr auto ZomborgExtra = 0x924; // Size: 4, Type: int32_t
			constexpr auto SettlePunishTypes = 0x928; // Size: 16, Type: struct TArray<enum class ESCMPlayerPunishType>
			constexpr auto StrategyConditionIDs = 0x938; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto SettlementDisplayStrategyID = 0x948; // Size: 4, Type: int32_t
			constexpr auto PlayerOutPath = 0x94f; // Size: 1, Type: enum class ESCMPlayerOutPath
			constexpr auto UsedCharacterIDs = 0x950; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto bPresettling = 0x960; // Size: 1, Type: bool
			constexpr auto bHasSettled = 0x961; // Size: 1, Type: bool
			constexpr auto bIsPlayerBattleEnd = 0x962; // Size: 1, Type: bool
			constexpr auto InteractValue = 0x964; // Size: 4, Type: int32_t
			constexpr auto LastInteractTime = 0x968; // Size: 4, Type: float
			constexpr auto DamageFactor = 0x96c; // Size: 4, Type: float
			constexpr auto VehicleProbability = 0x970; // Size: 4, Type: float
			constexpr auto bIsTimeoutPlayer = 0x974; // Size: 1, Type: bool
			constexpr auto bShowBattlePrompt = 0x975; // Size: 1, Type: char
			constexpr auto ExposeLocationMap = 0x998; // Size: 88, Type: struct FExposeLocationMap
			constexpr auto ExposeLocationArray = 0x9f0; // Size: 16, Type: struct TArray<struct ASolarPlayerState*>
			constexpr auto PlayerLocation = 0xa00; // Size: 12, Type: struct FVector
			constexpr auto ExposeTo = 0xa10; // Size: 8, Type: struct ASolarPlayerState*
			constexpr auto SkydivingLeaderPosInTeam = 0xa20; // Size: 4, Type: int32_t
			constexpr auto SkydivingFollowFormationPos = 0xa24; // Size: 1, Type: char
			constexpr auto SkydivingState = 0xa2c; // Size: 1, Type: enum class ESkydivingState
			constexpr auto AchievementComponent = 0xa30; // Size: 8, Type: struct USolarAchievementComponent*
			constexpr auto PreCompletedAchievementIDs = 0xa40; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto PlayerLevel = 0xa50; // Size: 4, Type: int32_t
			constexpr auto PlayerExperience = 0xa54; // Size: 4, Type: int32_t
			constexpr auto HistoryShieldUpgradeItemNum = 0xa58; // Size: 4, Type: int32_t
			constexpr auto TrackInfo = 0xa78; // Size: 8, Type: struct ASpatializeInfoTrack*
			constexpr auto TrackMaxRevealDistance = 0xa80; // Size: 4, Type: float
			constexpr auto AppLifetimeState = 0xa84; // Size: 1, Type: enum class EAppLifetimeState
			constexpr auto TailFlameId = 0xa88; // Size: 4, Type: int32_t
			constexpr auto Team = 0xa90; // Size: 8, Type: struct ASolarTeamInfo*
			constexpr auto BattleWeaponDataArray = 0xaa8; // Size: 16, Type: struct TArray<struct FSolarBattleWeaponData>
			constexpr auto HeroPickInfo = 0xab8; // Size: 8, Type: struct AHeroPickInfo*
	}
} 
