namespace offsets
{
	namespace UPlayerOperationList
	{
			constexpr auto CollectedLayout = 0x358; // Size: 80, Type: struct TMap<struct FString, struct UWidget*>
			constexpr auto WidgetVisibilityState = 0x3f8; // Size: 1, Type: enum class EPlayerWidgetState
			constexpr auto Panel_AngleView = 0x400; // Size: 8, Type: struct UCanvasPanel*
			constexpr auto FlyActiveControl = 0x408; // Size: 8, Type: struct UWidgetControlGroup*
			constexpr auto JetActiveControl = 0x410; // Size: 8, Type: struct UWidgetControlGroup*
			constexpr auto FreeLookPad = 0x418; // Size: 8, Type: struct USolarMovablePad*
			constexpr auto FreeLookIcon = 0x420; // Size: 8, Type: struct UImage*
			constexpr auto Img_SprintActive = 0x428; // Size: 8, Type: struct UImage*
			constexpr auto Img_SprintLock = 0x430; // Size: 8, Type: struct UImage*
			constexpr auto FX_CircleLoop = 0x438; // Size: 8, Type: struct UImage*
			constexpr auto PressedFreeLook = 0x440; // Size: 40, Type: struct TSoftObjectPtr<UPaperSprite>
			constexpr auto ReleasedFreeLook = 0x468; // Size: 40, Type: struct TSoftObjectPtr<UPaperSprite>
			constexpr auto SkydiveSprintImage = 0x490; // Size: 40, Type: struct TSoftObjectPtr<UTexture>
			constexpr auto SkydiveSprintHoveredImage = 0x4b8; // Size: 40, Type: struct TSoftObjectPtr<UTexture>
			constexpr auto VehicleAutoMoveImage = 0x4e0; // Size: 40, Type: struct TSoftObjectPtr<UTexture>
			constexpr auto VehicleAutoMoveHoveredImage = 0x508; // Size: 40, Type: struct TSoftObjectPtr<UTexture>
			constexpr auto Panel_SpectateHide = 0x530; // Size: 8, Type: struct UCanvasPanel*
			constexpr auto Panel_CountDown = 0x538; // Size: 8, Type: struct UHUDCountdownWidget*
			constexpr auto BT_Jump = 0x540; // Size: 8, Type: struct USolarInputButton*
			constexpr auto BTN_TeamRescue = 0x548; // Size: 8, Type: struct UButton*
			constexpr auto WidgetSwitcher_RescueBTN = 0x550; // Size: 8, Type: struct UWidgetSwitcher*
			constexpr auto UI_PassiveHead_item = 0x558; // Size: 8, Type: struct UHUDPassiveHeadWidget*
			constexpr auto Panel_Crouch = 0x560; // Size: 8, Type: struct UCanvasPanel*
			constexpr auto Sprint = 0x568; // Size: 8, Type: struct UCanvasPanel*
			constexpr auto SprintActiveOncePanel = 0x570; // Size: 8, Type: struct UCanvasPanel*
			constexpr auto Txt_JoystickLock = 0x578; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto FX_CircleOnce_Anim = 0x580; // Size: 8, Type: struct UWidgetAnimation*
			constexpr auto FX_CircleLoop_Anim = 0x588; // Size: 8, Type: struct UWidgetAnimation*
			constexpr auto JoystickLockTipsSprintTextID = 0x590; // Size: 4, Type: int32_t
			constexpr auto JoystickLockTipsSkydiveTextID = 0x594; // Size: 4, Type: int32_t
			constexpr auto BTN_BuyResurrection = 0x598; // Size: 8, Type: struct UButton*
			constexpr auto Panel_ShieldUpgrade = 0x5a0; // Size: 8, Type: struct UCanvasPanel*
			constexpr auto Switcher_State = 0x5a8; // Size: 8, Type: struct UWidgetSwitcher*
			constexpr auto Panel_Btn = 0x5b0; // Size: 8, Type: struct UCanvasPanel*
			constexpr auto Panel_CD = 0x5b8; // Size: 8, Type: struct UCanvasPanel*
			constexpr auto Btn_ShiledUpgrade = 0x5c0; // Size: 8, Type: struct USolarButton*
			constexpr auto Img_Light = 0x5c8; // Size: 8, Type: struct UImage*
			constexpr auto Img_Enter_Light_2 = 0x5d0; // Size: 8, Type: struct UImage*
			constexpr auto Img_Enter_Light_3 = 0x5d8; // Size: 8, Type: struct UImage*
			constexpr auto Img_Loop_Light_2 = 0x5e0; // Size: 8, Type: struct UImage*
			constexpr auto Img_Loop_Light_3 = 0x5e8; // Size: 8, Type: struct UImage*
			constexpr auto Img_Loop_Arrow_4 = 0x5f0; // Size: 8, Type: struct UImage*
			constexpr auto Img_Shield = 0x600; // Size: 8, Type: struct UImage*
			constexpr auto Text_GameProgressTime = 0x608; // Size: 8, Type: struct UTextBlock*
			constexpr auto BTN_GameProgressCancel = 0x610; // Size: 8, Type: struct UButton*
			constexpr auto Image_GameProgressBar = 0x618; // Size: 8, Type: struct UGaugeImage*
			constexpr auto Anim_ShieldUpgrade_Enter = 0x620; // Size: 8, Type: struct UWidgetAnimation*
			constexpr auto Anim_ShieldUpgrade_Exit = 0x628; // Size: 8, Type: struct UWidgetAnimation*
			constexpr auto CircleOnceAnimInterval = 0x630; // Size: 4, Type: float
			constexpr auto FastReliefSkillCharacterID = 0x634; // Size: 4, Type: int32_t
			constexpr auto BT_ElectricShop = 0x688; // Size: 8, Type: struct USolarButton*
			constexpr auto EShopHUDCheckTime = 0x69c; // Size: 4, Type: float
			constexpr auto EShopHUDName = 0x6a0; // Size: 16, Type: struct FString
			constexpr auto Vehicle_Drive = 0x6b8; // Size: 8, Type: struct UHorizontalBox*
			constexpr auto Vehicle_Passenger = 0x6c0; // Size: 8, Type: struct UHorizontalBox*
			constexpr auto Vehicle_Passenger_PC = 0x6c8; // Size: 8, Type: struct UHorizontalBox*
			constexpr auto Vehicle_Repair_Status = 0x6d0; // Size: 8, Type: struct UCanvasPanel*
			constexpr auto Panel_Vehicle_Drive_Passenger = 0x6d8; // Size: 8, Type: struct UCanvasPanel*
			constexpr auto UI_Vehicle_Health = 0x6e0; // Size: 8, Type: struct USolarVehicleHealthWidget*
			constexpr auto WidgetSwitcher_VehicleRepair = 0x6e8; // Size: 8, Type: struct UWidgetSwitcher*
			constexpr auto WalkJoyStick = 0x6f0; // Size: 8, Type: struct UWalkWidgetNew*
			constexpr auto bJoyStickVisible = 0x6f8; // Size: 1, Type: char
			constexpr auto Panel_FollowDance = 0x700; // Size: 8, Type: struct UCanvasPanel*
			constexpr auto Btn_FollowDance = 0x708; // Size: 8, Type: struct USolarInputButton*
	}
} 
