namespace offsets
{
	namespace UPrimitiveComponent
	{
			constexpr auto MinDrawDistance = 0x320; // Size: 4, Type: float
			constexpr auto LDMaxDrawDistance = 0x324; // Size: 4, Type: float
			constexpr auto CachedMaxDrawDistance = 0x328; // Size: 4, Type: float
			constexpr auto MinScreenSizeCulling = 0x32c; // Size: 4, Type: float
			constexpr auto DepthPriorityGroup = 0x330; // Size: 1, Type: enum class ESceneDepthPriorityGroup
			constexpr auto ViewOwnerDepthPriorityGroup = 0x331; // Size: 1, Type: enum class ESceneDepthPriorityGroup
			constexpr auto IndirectLightingCacheQuality = 0x332; // Size: 1, Type: enum class EIndirectLightingCacheQuality
			constexpr auto LightmapType = 0x333; // Size: 1, Type: enum class ELightmapType
			constexpr auto bUseMaxLODAsImposter = 0x334; // Size: 1, Type: char
			constexpr auto bBatchImpostersAsInstances = 0x334; // Size: 1, Type: char
			constexpr auto bNeverDistanceCull = 0x334; // Size: 1, Type: char
			constexpr auto bAlwaysCreatePhysicsState = 0x334; // Size: 1, Type: char
			constexpr auto bGenerateOverlapEvents = 0x335; // Size: 1, Type: char
			constexpr auto bMultiBodyOverlap = 0x335; // Size: 1, Type: char
			constexpr auto bTraceComplexOnMove = 0x335; // Size: 1, Type: char
			constexpr auto bReturnMaterialOnMove = 0x335; // Size: 1, Type: char
			constexpr auto bUseViewOwnerDepthPriorityGroup = 0x335; // Size: 1, Type: char
			constexpr auto bAllowCullDistanceVolume = 0x335; // Size: 1, Type: char
			constexpr auto bHasMotionBlurVelocityMeshes = 0x335; // Size: 1, Type: char
			constexpr auto bVisibleInReflectionCaptures = 0x335; // Size: 1, Type: char
			constexpr auto bVisibleInRayTracing = 0x336; // Size: 1, Type: char
			constexpr auto bRenderInMainPass = 0x336; // Size: 1, Type: char
			constexpr auto bRenderInDepthPass = 0x336; // Size: 1, Type: char
			constexpr auto bReceivesDecals = 0x336; // Size: 1, Type: char
			constexpr auto bOwnerNoSee = 0x336; // Size: 1, Type: char
			constexpr auto bOnlyOwnerSee = 0x336; // Size: 1, Type: char
			constexpr auto bTreatAsBackgroundForOcclusion = 0x336; // Size: 1, Type: char
			constexpr auto bUseAsOccluder = 0x336; // Size: 1, Type: char
			constexpr auto bIgnoreOcclusionCull = 0x337; // Size: 1, Type: char
			constexpr auto bSelectable = 0x337; // Size: 1, Type: char
			constexpr auto bForceMipStreaming = 0x337; // Size: 1, Type: char
			constexpr auto bHasPerInstanceHitProxies = 0x337; // Size: 1, Type: char
			constexpr auto CastShadow = 0x337; // Size: 1, Type: char
			constexpr auto bAffectDynamicIndirectLighting = 0x337; // Size: 1, Type: char
			constexpr auto bAffectDistanceFieldLighting = 0x337; // Size: 1, Type: char
			constexpr auto bCastDynamicShadow = 0x337; // Size: 1, Type: char
			constexpr auto bCastStaticShadow = 0x338; // Size: 1, Type: char
			constexpr auto bCastVolumetricTranslucentShadow = 0x338; // Size: 1, Type: char
			constexpr auto bSelfShadowOnly = 0x338; // Size: 1, Type: char
			constexpr auto bForceGenLightmap = 0x338; // Size: 1, Type: char
			constexpr auto bCastFarShadow = 0x338; // Size: 1, Type: char
			constexpr auto bCastInsetShadow = 0x338; // Size: 1, Type: char
			constexpr auto bCastCinematicShadow = 0x338; // Size: 1, Type: char
			constexpr auto bCastHiddenShadow = 0x338; // Size: 1, Type: char
			constexpr auto bCastShadowAsTwoSided = 0x339; // Size: 1, Type: char
			constexpr auto bLightAsIfStatic = 0x339; // Size: 1, Type: char
			constexpr auto bLightAttachmentsAsGroup = 0x339; // Size: 1, Type: char
			constexpr auto bExcludeFromLightAttachmentGroup = 0x339; // Size: 1, Type: char
			constexpr auto bReceiveMobileCSMShadows = 0x339; // Size: 1, Type: char
			constexpr auto bSingleSampleShadowFromStationaryLights = 0x339; // Size: 1, Type: char
			constexpr auto bIgnoreRadialImpulse = 0x339; // Size: 1, Type: char
			constexpr auto bIgnoreRadialForce = 0x339; // Size: 1, Type: char
			constexpr auto bApplyImpulseOnDamage = 0x33a; // Size: 1, Type: char
			constexpr auto bReplicatePhysicsToAutonomousProxy = 0x33a; // Size: 1, Type: char
			constexpr auto bFillCollisionUnderneathForNavmesh = 0x33a; // Size: 1, Type: char
			constexpr auto AlwaysLoadOnClient = 0x33a; // Size: 1, Type: char
			constexpr auto AlwaysLoadOnServer = 0x33a; // Size: 1, Type: char
			constexpr auto bUseEditorCompositing = 0x33a; // Size: 1, Type: char
			constexpr auto bRenderCustomDepth = 0x33a; // Size: 1, Type: char
			constexpr auto bRenderMainPassStencil = 0x33a; // Size: 1, Type: char
			constexpr auto bHasCustomNavigableGeometry = 0x33c; // Size: 1, Type: enum class EHasCustomNavigableGeometry
			constexpr auto CanCharacterStepUpOn = 0x33e; // Size: 1, Type: enum class ECanBeCharacterBase
			constexpr auto LightingChannels = 0x33f; // Size: 1, Type: struct FLightingChannels
			constexpr auto CustomDepthStencilWriteMask = 0x340; // Size: 1, Type: enum class ERendererStencilMask
			constexpr auto CustomDepthStencilValue = 0x344; // Size: 4, Type: int32_t
			constexpr auto MainPassDepthStencilValue = 0x348; // Size: 4, Type: int32_t
			constexpr auto CustomPrimitiveData = 0x350; // Size: 16, Type: struct FCustomPrimitiveData
			constexpr auto CustomPrimitiveDataInternal = 0x360; // Size: 16, Type: struct FCustomPrimitiveData
			constexpr auto TranslucencySortPriority = 0x370; // Size: 4, Type: int32_t
			constexpr auto VisibilityId = 0x374; // Size: 4, Type: int32_t
			constexpr auto RuntimeVirtualTextures = 0x378; // Size: 16, Type: struct TArray<struct URuntimeVirtualTexture*>
			constexpr auto VirtualTextureLodBias = 0x388; // Size: 1, Type: int8_t
			constexpr auto VirtualTextureCullMips = 0x389; // Size: 1, Type: int8_t
			constexpr auto VirtualTextureMinCoverage = 0x38a; // Size: 1, Type: int8_t
			constexpr auto VirtualTextureRenderPassType = 0x38b; // Size: 1, Type: enum class ERuntimeVirtualTextureMainPassType
			constexpr auto LpvBiasMultiplier = 0x390; // Size: 4, Type: float
			constexpr auto BoundsScale = 0x39c; // Size: 4, Type: float
			constexpr auto MoveIgnoreActors = 0x3b0; // Size: 16, Type: struct TArray<struct AActor*>
			constexpr auto MoveIgnoreComponents = 0x3c0; // Size: 16, Type: struct TArray<struct UPrimitiveComponent*>
			constexpr auto BodyInstance = 0x3e0; // Size: 304, Type: struct FBodyInstance
			constexpr auto OnComponentHit = 0x510; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnComponentBeginOverlap = 0x511; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnComponentEndOverlap = 0x512; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnComponentWake = 0x513; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnComponentSleep = 0x514; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnBeginCursorOver = 0x516; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnEndCursorOver = 0x517; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnClicked = 0x518; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnReleased = 0x519; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnInputTouchBegin = 0x51a; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnInputTouchEnd = 0x51b; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnInputTouchEnter = 0x51c; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnInputTouchLeave = 0x51d; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto LODParentPrimitive = 0x538; // Size: 8, Type: struct UPrimitiveComponent*
	}
} 
