namespace offsets
{
	namespace USolarGameInstanceBase
	{
			constexpr auto LoginMap = 0x350; // Size: 24, Type: struct FSoftObjectPath
			constexpr auto LobbyMap = 0x368; // Size: 24, Type: struct FSoftObjectPath
			constexpr auto EntryMap = 0x380; // Size: 24, Type: struct FSoftObjectPath
			constexpr auto GameMap = 0x398; // Size: 24, Type: struct FSoftObjectPath
			constexpr auto SettlementMap = 0x3b0; // Size: 24, Type: struct FSoftObjectPath
			constexpr auto ConfigServerMap = 0x3c8; // Size: 24, Type: struct FSoftObjectPath
			constexpr auto ConfigBattleAddr = 0x3e0; // Size: 16, Type: struct FString
			constexpr auto ConfigBattlePort = 0x3f0; // Size: 4, Type: int32_t
			constexpr auto ConfigBackendAddr = 0x3f8; // Size: 16, Type: struct FString
			constexpr auto ConfigBackendPort = 0x408; // Size: 4, Type: int32_t
			constexpr auto BuildNumber = 0x40c; // Size: 4, Type: int32_t
			constexpr auto SaveGameClass = 0x410; // Size: 40, Type: struct TSoftClassPtr<UObject>
			constexpr auto DefaultOperationLayout = 0x438; // Size: 24, Type: struct FSoftClassPath
			constexpr auto DefaultLockSettings = 0x450; // Size: 24, Type: struct FSoftClassPath
			constexpr auto ReplayManagerClass = 0x468; // Size: 24, Type: struct FSoftClassPath
			constexpr auto DefaultGameModeLockSettings = 0x480; // Size: 24, Type: struct FSoftClassPath
			constexpr auto bNeedRebootButNot = 0x498; // Size: 1, Type: bool
			constexpr auto LastChoosedVoiceLangID = 0x49c; // Size: 4, Type: int32_t
			constexpr auto CachedNetworkErrorString = 0x4a0; // Size: 16, Type: struct FString
			constexpr auto CachedDefaultOperationLayout = 0x4b0; // Size: 8, Type: struct USolarOperationUIElement*
			constexpr auto bBaseManagersInit = 0x4b8; // Size: 1, Type: bool
			constexpr auto bGameManagersInit = 0x4b9; // Size: 1, Type: bool
			constexpr auto bLuaManagersInit = 0x4ba; // Size: 1, Type: bool
			constexpr auto OnBaseManagersInit = 0x4c0; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnGameManagersInit = 0x4d0; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnLuaManagersInit = 0x4e0; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto GameArgsManager = 0x668; // Size: 8, Type: struct UGameArgs*
			constexpr auto UIManager = 0x670; // Size: 8, Type: struct UUIManager*
			constexpr auto UINavigationManager = 0x678; // Size: 8, Type: struct UUINavigationManager*
			constexpr auto SolarInputMappingManager = 0x680; // Size: 8, Type: struct USolarInputMappingManager*
			constexpr auto SolarTimerManager = 0x688; // Size: 8, Type: struct USolarTimerManager*
			constexpr auto MainPlayerModel = 0x690; // Size: 8, Type: struct USolarMainPlayerModel*
			constexpr auto GameConfigManager = 0x698; // Size: 8, Type: struct USolarGameConfigManager*
			constexpr auto BattlePassConfigInfo = 0x6a0; // Size: 8, Type: struct UBattlePassConfigInfo*
			constexpr auto SolarLuaHelper = 0x6a8; // Size: 8, Type: struct USolarLuaHelper*
			constexpr auto SolarAnoHelper = 0x6b0; // Size: 8, Type: struct USolarAnoHelper*
			constexpr auto SolarTableManager = 0x6b8; // Size: 8, Type: struct USolarTableManager*
			constexpr auto SolarTcpNetworkManager = 0x6c0; // Size: 8, Type: struct USolarTcpNetworkManager*
			constexpr auto SolarUDPManager = 0x6c8; // Size: 8, Type: struct USolarUDPManager*
			constexpr auto SolarAssetManager = 0x6d0; // Size: 8, Type: struct USolarAssetManager*
			constexpr auto SolarItemManager = 0x6d8; // Size: 8, Type: struct USolarItemManager*
			constexpr auto SolarInteractableManager = 0x6e0; // Size: 8, Type: struct USolarInteractableManager*
			constexpr auto SolarPlatformHelper = 0x6e8; // Size: 8, Type: struct USolarPlatformHelper*
			constexpr auto SolarMapManager = 0x6f0; // Size: 8, Type: struct USolarMapManager*
			constexpr auto WeaponGrowthManager = 0x6f8; // Size: 8, Type: struct UWeaponGrowthManager*
			constexpr auto SolarAkGameObject = 0x700; // Size: 8, Type: struct USolarAkGameObject*
			constexpr auto SolarIMChatObject = 0x708; // Size: 8, Type: struct UIMChatObject*
			constexpr auto SolarLuaManager = 0x710; // Size: 8, Type: struct USolarLuaManager*
			constexpr auto SolarGameStatistics = 0x718; // Size: 8, Type: struct USolarGameStatistics*
			constexpr auto WeaponMergeMeshManager = 0x720; // Size: 8, Type: struct USolarWeaponMergeMeshManager*
			constexpr auto CrashReportManager = 0x728; // Size: 8, Type: struct UCrashReportManager*
			constexpr auto SolarPopPanelManager = 0x730; // Size: 8, Type: struct USolarPopPanelManager*
			constexpr auto SolarApplicationLifetimeManager = 0x738; // Size: 8, Type: struct USolarApplicationLifetimeManager*
			constexpr auto SolarHomeActorManager = 0x740; // Size: 8, Type: struct USolarHomeActorManager*
			constexpr auto SolarGameplayLoggger = 0x748; // Size: 8, Type: struct USolarGameplayLogger*
			constexpr auto SolarAttributeSubSystem = 0x750; // Size: 8, Type: struct USolarAttributeSubSystem*
			constexpr auto CustomizedGameManager = 0x758; // Size: 8, Type: struct USCustomizedGameModeManager*
			constexpr auto SolarRedHintMgr = 0x760; // Size: 8, Type: struct USolarRedHintManager*
			constexpr auto SolarGameModeSelectionMgr = 0x768; // Size: 8, Type: struct USolarGameModeSelectionManager*
			constexpr auto SolarPingFpsMgr = 0x770; // Size: 8, Type: struct USolarPingFpsManager*
			constexpr auto SolarGameUserSettingsMgr = 0x778; // Size: 8, Type: struct USolarGameUserSettingsMgr*
			constexpr auto SolarLoginManager = 0x780; // Size: 8, Type: struct USolarLoginManager*
			constexpr auto SolarLockSettingsMgr = 0x788; // Size: 8, Type: struct USolarLockSettingsMgr*
			constexpr auto SolarGameProgressMgr = 0x790; // Size: 8, Type: struct USolarGameProgressManager*
			constexpr auto SolarABTestManager = 0x798; // Size: 8, Type: struct USolarABTestManager*
			constexpr auto SolarHttpManager = 0x7a0; // Size: 8, Type: struct USolarHttpManager*
			constexpr auto SolarActivityManager = 0x7a8; // Size: 8, Type: struct USolarActivityManager*
			constexpr auto SolarTutorialManager = 0x7b0; // Size: 8, Type: struct USolarTutorialManager*
			constexpr auto SolarReplayManager = 0x7b8; // Size: 8, Type: struct USolarReplayManager*
			constexpr auto SolarSaveGame = 0x7c0; // Size: 8, Type: struct USolarSaveGame*
			constexpr auto SettlementManagerClass = 0x7c8; // Size: 40, Type: struct TSoftClassPtr<UObject>
			constexpr auto SettlementManager = 0x7f0; // Size: 8, Type: struct USettlementStageManager*
			constexpr auto CrossLevelDataMgr = 0x7f8; // Size: 8, Type: struct UCGMCrossLevelDataMgr*
			constexpr auto SolarGraphicSettingsClass = 0x818; // Size: 40, Type: struct TSoftClassPtr<UObject>
			constexpr auto LuaDataAccessUtils = 0x840; // Size: 8, Type: struct USolarAccessLuaDataUtils*
			constexpr auto SolarAkSoundManager = 0x848; // Size: 8, Type: struct USolarAkSoundManager*
			constexpr auto bIsDedicatedServerStressTest = 0x850; // Size: 1, Type: bool
			constexpr auto KeyMappingManager = 0x858; // Size: 8, Type: struct UKeyMappingManager*
			constexpr auto SolarEasyAntiCheatManager = 0x860; // Size: 8, Type: struct USolarEasyAntiCheatManager*
			constexpr auto SolarSpecialEffectsManager = 0x868; // Size: 8, Type: struct USolarSpecialEffectsMgr*
			constexpr auto SolarPakHashManager = 0x870; // Size: 8, Type: struct UPakHashManager*
			constexpr auto SolarFontManager = 0x878; // Size: 8, Type: struct USolarFontManager*
			constexpr auto SolarGraphicSettings = 0x880; // Size: 8, Type: struct USolarGraphicSettings*
			constexpr auto AndroidInputManager = 0x888; // Size: 8, Type: struct UAndroidInputManager*
			constexpr auto OnPatchComplete = 0x8a0; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnTouchInputDelegate = 0x8b0; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto CachedRegistedActors = 0x8c0; // Size: 80, Type: struct FRegistedActorContainer
			constexpr auto IsHotPatched = 0x928; // Size: 1, Type: bool
			constexpr auto bCheatedInGame = 0x92c; // Size: 1, Type: bool
			constexpr auto KickOutReason = 0x930; // Size: 24, Type: struct FText
			constexpr auto OnSsmDSGetConfigSuccess = 0x948; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto AntiCheatSettings = 0x958; // Size: 16, Type: struct TArray<struct FAntiCheatSetting>
			constexpr auto ScreenshotConfig = 0x968; // Size: 80, Type: struct FScreenshotConfig
	}
} 
