namespace offsets
{
	namespace UUI_Settings_Item_Slot_C
	{
			constexpr auto UberGraphFrame = 0x348; // Size: 8, Type: struct FPointerToUberGraphFrame
			constexpr auto Btn_Info_Mark = 0x350; // Size: 8, Type: struct USolarButton*
			constexpr auto btn_jump = 0x358; // Size: 8, Type: struct USolarButton*
			constexpr auto Btn_Universal = 0x360; // Size: 8, Type: struct USolarCheckButton*
			constexpr auto CheckBoxGroup_Gryo = 0x368; // Size: 8, Type: struct UCheckBoxGroup*
			constexpr auto EditText_percent = 0x370; // Size: 8, Type: struct USpinBox*
			constexpr auto Overlay_1 = 0x378; // Size: 8, Type: struct UOverlay*
			constexpr auto Panel_CheckBox = 0x380; // Size: 8, Type: struct UCanvasPanel*
			constexpr auto Panel_Common = 0x388; // Size: 8, Type: struct UCanvasPanel*
			constexpr auto Panel_Jump = 0x390; // Size: 8, Type: struct UCanvasPanel*
			constexpr auto Panel_SetPercent = 0x398; // Size: 8, Type: struct UCanvasPanel*
			constexpr auto Panel_ToggleButton = 0x3a0; // Size: 8, Type: struct UCanvasPanel*
			constexpr auto ProgressBar = 0x3a8; // Size: 8, Type: struct UProgressBar*
			constexpr auto SizeBox = 0x3b0; // Size: 8, Type: struct USizeBox*
			constexpr auto SizeBox_14 = 0x3b8; // Size: 8, Type: struct USizeBox*
			constexpr auto SizeBox_15 = 0x3c0; // Size: 8, Type: struct USizeBox*
			constexpr auto SizeBox_16 = 0x3c8; // Size: 8, Type: struct USizeBox*
			constexpr auto SizeBox_17 = 0x3d0; // Size: 8, Type: struct USizeBox*
			constexpr auto SizeBox_18 = 0x3d8; // Size: 8, Type: struct USizeBox*
			constexpr auto Slider = 0x3e0; // Size: 8, Type: struct USlider*
			constexpr auto SolarCheckBox_2 = 0x3e8; // Size: 8, Type: struct USolarCheckBox*
			constexpr auto SolarCheckBox_3 = 0x3f0; // Size: 8, Type: struct USolarCheckBox*
			constexpr auto SolarCheckBox_4 = 0x3f8; // Size: 8, Type: struct USolarCheckBox*
			constexpr auto SolarCheckBox_5 = 0x400; // Size: 8, Type: struct USolarCheckBox*
			constexpr auto SolarCheckBox_6 = 0x408; // Size: 8, Type: struct USolarCheckBox*
			constexpr auto Switch_On = 0x410; // Size: 8, Type: struct UUI_Component_Switch_C*
			constexpr auto Text_Title = 0x418; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Text_Universal = 0x420; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Tips_Marker = 0x428; // Size: 8, Type: struct UUI_Setting_Tips_C*
			constexpr auto Txt_CheckBox_Off_2 = 0x430; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Txt_CheckBox_Off_3 = 0x438; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Txt_CheckBox_Off_4 = 0x440; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Txt_CheckBox_Off_5 = 0x448; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Txt_CheckBox_Off_6 = 0x450; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Txt_CheckBox_On_2 = 0x458; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Txt_CheckBox_On_3 = 0x460; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Txt_CheckBox_On_4 = 0x468; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Txt_CheckBox_On_5 = 0x470; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Txt_CheckBox_On_6 = 0x478; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Txt_ReadOnly = 0x480; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto UI_Component_Switch = 0x488; // Size: 8, Type: struct UUI_Component_Switch_C*
			constexpr auto WidgetSwitcher_1 = 0x490; // Size: 8, Type: struct UWidgetSwitcher*
			constexpr auto TitleText = 0x498; // Size: 24, Type: struct FText
			constexpr auto IsLocText = 0x4b0; // Size: 1, Type: bool
			constexpr auto LocID = 0x4b4; // Size: 4, Type: int32_t
			constexpr auto PreviewLang = 0x4b8; // Size: 1, Type: enum class ESolarSupportLanguages
			constexpr auto SetSpecialLang = 0x4c0; // Size: 24, Type: struct FSlateFontSizeForLang
			constexpr auto Size = 0x4d8; // Size: 4, Type: float
			constexpr auto IsTips = 0x4dc; // Size: 1, Type: bool
			constexpr auto IsCheckBtn = 0x4dd; // Size: 1, Type: bool
			constexpr auto CheckBoxWidth = 0x4e0; // Size: 4, Type: float
			constexpr auto IsCheckPositionBottom = 0x4e4; // Size: 1, Type: bool
			constexpr auto CheckGroupListData = 0x4e8; // Size: 16, Type: struct TArray<struct FLocLangTextParam>
			constexpr auto Txt_CheckBox_OnArray = 0x4f8; // Size: 16, Type: struct TArray<struct USolarTextBlock*>
			constexpr auto Txt_CheckBox_OffArray = 0x508; // Size: 16, Type: struct TArray<struct USolarTextBlock*>
			constexpr auto SolarCheckBox_Array = 0x518; // Size: 16, Type: struct TArray<struct USolarCheckBox*>
			constexpr auto OnSwitchStateChanged = 0x528; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnSwitchClicked = 0x538; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnCheckBoxStateChangedEvent = 0x548; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnCheckBoxStateChangedEventEx = 0x558; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto IsSwitchOn = 0x568; // Size: 1, Type: bool
			constexpr auto IsSlider = 0x569; // Size: 1, Type: bool
			constexpr auto Is Jump = 0x56a; // Size: 1, Type: bool
	}
} 
