namespace offsets
{
	namespace UUIBackpackWidget
	{
			constexpr auto Weapon_Part_Muzzle = 0x348; // Size: 8, Type: struct UUIWeaponPartWidget*
			constexpr auto Weapon_Part_Grip = 0x350; // Size: 8, Type: struct UUIWeaponPartWidget*
			constexpr auto Weapon_Part_Clip = 0x358; // Size: 8, Type: struct UUIWeaponPartWidget*
			constexpr auto Weapon_Part_Scope = 0x360; // Size: 8, Type: struct UUIWeaponPartWidget*
			constexpr auto Weapon_Part_GunStock = 0x368; // Size: 8, Type: struct UUIWeaponPartWidget*
			constexpr auto TextBlock_item_2 = 0x370; // Size: 8, Type: struct URichTextBlock*
			constexpr auto TextBlock_item_3 = 0x378; // Size: 8, Type: struct URichTextBlock*
			constexpr auto TextBlock_item_4 = 0x380; // Size: 8, Type: struct URichTextBlock*
			constexpr auto TextBlock_item_5 = 0x388; // Size: 8, Type: struct URichTextBlock*
			constexpr auto TextBlock_item_6 = 0x390; // Size: 8, Type: struct URichTextBlock*
			constexpr auto TextBlock_item_7 = 0x398; // Size: 8, Type: struct URichTextBlock*
			constexpr auto TextBlock_item_8 = 0x3a0; // Size: 8, Type: struct URichTextBlock*
			constexpr auto TextBlock_item_9 = 0x3a8; // Size: 8, Type: struct URichTextBlock*
			constexpr auto TextBlock_item_10 = 0x3b0; // Size: 8, Type: struct URichTextBlock*
			constexpr auto dragitem_item_2 = 0x3b8; // Size: 8, Type: struct UUIDragWidget*
			constexpr auto dragitem_item_3 = 0x3c0; // Size: 8, Type: struct UUIDragWidget*
			constexpr auto dragitem_item_4 = 0x3c8; // Size: 8, Type: struct UUIDragWidget*
			constexpr auto dragitem_item_5 = 0x3d0; // Size: 8, Type: struct UUIDragWidget*
			constexpr auto dragitem_item_6 = 0x3d8; // Size: 8, Type: struct UUIDragWidget*
			constexpr auto dragitem_item_7 = 0x3e0; // Size: 8, Type: struct UUIDragWidget*
			constexpr auto dragitem_item_8 = 0x3e8; // Size: 8, Type: struct UUIDragWidget*
			constexpr auto dragitem_item_9 = 0x3f0; // Size: 8, Type: struct UUIDragWidget*
			constexpr auto dragitem_item_10 = 0x3f8; // Size: 8, Type: struct UUIDragWidget*
			constexpr auto dragitem_Relive = 0x400; // Size: 8, Type: struct UUIDragWidget*
			constexpr auto Weapon_A = 0x408; // Size: 8, Type: struct UUIBackpackWeaponWidget*
			constexpr auto Weapon_B = 0x410; // Size: 8, Type: struct UUIBackpackWeaponWidget*
			constexpr auto dragitem_Summon = 0x418; // Size: 8, Type: struct UUIDragWidget*
			constexpr auto Panel_Empty = 0x420; // Size: 8, Type: struct UCanvasPanel*
			constexpr auto Img_Summon_Bg = 0x428; // Size: 8, Type: struct UImage*
			constexpr auto dragitem_equip_2 = 0x430; // Size: 8, Type: struct UUIDragWidget*
			constexpr auto dragitem_equip_3 = 0x438; // Size: 8, Type: struct UUIDragWidget*
			constexpr auto dragitem_equip_4 = 0x440; // Size: 8, Type: struct UUIDragWidget*
			constexpr auto dragitem_equip_5 = 0x448; // Size: 8, Type: struct UUIDragWidget*
			constexpr auto Item_BG_2 = 0x450; // Size: 8, Type: struct UImage*
			constexpr auto Item_BG_3 = 0x458; // Size: 8, Type: struct UImage*
			constexpr auto Item_BG_4 = 0x460; // Size: 8, Type: struct UImage*
			constexpr auto Item_BG_5 = 0x468; // Size: 8, Type: struct UImage*
			constexpr auto Item_Quality_BG_2 = 0x470; // Size: 8, Type: struct UImage*
			constexpr auto Item_Quality_BG_3 = 0x478; // Size: 8, Type: struct UImage*
			constexpr auto Item_Quality_BG_4 = 0x480; // Size: 8, Type: struct UImage*
			constexpr auto Item_Quality_BG_5 = 0x488; // Size: 8, Type: struct UImage*
			constexpr auto Equip_Icon_2 = 0x490; // Size: 8, Type: struct UImage*
			constexpr auto Equip_Icon_3 = 0x498; // Size: 8, Type: struct UImage*
			constexpr auto Equip_Icon_4 = 0x4a0; // Size: 8, Type: struct UImage*
			constexpr auto Equip_Icon_5 = 0x4a8; // Size: 8, Type: struct UImage*
			constexpr auto BtnShield = 0x4b0; // Size: 8, Type: struct UButton*
			constexpr auto BtnBattery = 0x4b8; // Size: 8, Type: struct UButton*
			constexpr auto BtnHorPush = 0x4c0; // Size: 8, Type: struct UButton*
			constexpr auto BtnVerPush = 0x4c8; // Size: 8, Type: struct UButton*
			constexpr auto BtnRespawn = 0x4d0; // Size: 8, Type: struct UButton*
			constexpr auto BtnSpecial = 0x4d8; // Size: 8, Type: struct UButton*
			constexpr auto BtnSMGAmmo = 0x4e0; // Size: 8, Type: struct UButton*
			constexpr auto Txt_Relive = 0x4e8; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Relive_Quality_BG = 0x4f0; // Size: 8, Type: struct UImage*
			constexpr auto Relive = 0x4f8; // Size: 8, Type: struct UOverlay*
			constexpr auto WidgetSwitcher_Mode = 0x500; // Size: 8, Type: struct UWidgetSwitcher*
			constexpr auto PickupPosition = 0x508; // Size: 8, Type: struct UCanvasPanel*
			constexpr auto Button_Close = 0x510; // Size: 8, Type: struct UButton*
			constexpr auto OnDropMask = 0x518; // Size: 8, Type: struct UUIDropMaskWidget*
			constexpr auto OnDropMask_2 = 0x520; // Size: 8, Type: struct UUIDropMaskWidget*
			constexpr auto Style_ItemNum = 0x528; // Size: 16, Type: struct FString
			constexpr auto Style_MaxNum = 0x538; // Size: 16, Type: struct FString
			constexpr auto EquipTexPrePath = 0x548; // Size: 16, Type: struct FString
			constexpr auto bWeaponPartInit = 0x558; // Size: 1, Type: bool
			constexpr auto ItemIDArray = 0x560; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto ItemTextArray = 0x570; // Size: 16, Type: struct TArray<struct URichTextBlock*>
			constexpr auto ItemDragWidgetArray = 0x580; // Size: 16, Type: struct TArray<struct UUIDragWidget*>
			constexpr auto EquipTypeArray = 0x590; // Size: 16, Type: struct TArray<enum class EItemType>
			constexpr auto EquipDragWidgetArray = 0x5a0; // Size: 16, Type: struct TArray<struct UUIDragWidget*>
			constexpr auto EquipBGArray = 0x5b0; // Size: 16, Type: struct TArray<struct UImage*>
			constexpr auto EquipQualityBGArray = 0x5c0; // Size: 16, Type: struct TArray<struct UImage*>
			constexpr auto EquipIconArray = 0x5d0; // Size: 16, Type: struct TArray<struct UImage*>
			constexpr auto EquipBtnArray = 0x5e0; // Size: 16, Type: struct TArray<struct UButton*>
			constexpr auto MaxUpgradeLevel = 0x5f0; // Size: 4, Type: int32_t
	}
} 
