namespace offsets
{
	namespace ASolarCharacter
	{
			constexpr auto PendingBeginPlay = 0x660; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnPlayerStatePossessDelegate = 0x688; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnPlayerStateRepDelegate = 0x698; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto SolarCharacterType = 0x6a8; // Size: 1, Type: enum class ESolarCharacterType
			constexpr auto CharacterCapsuleSizeOverride = 0x704; // Size: 8, Type: struct FVector2D
			constexpr auto bInRoom = 0x70d; // Size: 1, Type: bool
			constexpr auto ReconnectionParams = 0x73b; // Size: 1, Type: struct FReconnectionParams
			constexpr auto SolarAnimInstance = 0x758; // Size: 8, Type: struct USolarAnimInstance*
			constexpr auto SolarAnimInstances = 0x760; // Size: 80, Type: struct TMap<enum class ESpecAnimInstType, struct UAnimInstance*>
			constexpr auto BodyHitSoundCount = 0x7c4; // Size: 4, Type: int32_t
			constexpr auto BodyHitByPunchSoundCount = 0x7c8; // Size: 4, Type: int32_t
			constexpr auto ChargingPileQueue = 0x7d0; // Size: 16, Type: struct TArray<struct ASolarPile*>
			constexpr auto OnCharacterIDSet = 0x808; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnSkinIDSet = 0x818; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnCharacterSkinReset = 0x828; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto BodyScaleType = 0x838; // Size: 1, Type: enum class ECharacterBodyScaleType
			constexpr auto AssignedCharacterID = 0x83c; // Size: 4, Type: int32_t
			constexpr auto AssignedSkinID = 0x840; // Size: 4, Type: int32_t
			constexpr auto SkeletalOrnaments = 0x850; // Size: 80, Type: struct TMap<struct FGameplayTag, struct USkeletalMeshComponent*>
			constexpr auto StaticOrnaments = 0x8a0; // Size: 80, Type: struct TMap<struct FGameplayTag, struct UStaticMeshComponent*>
			constexpr auto ChildActorOrnaments = 0x8f0; // Size: 80, Type: struct TMap<struct FGameplayTag, struct UChildActorComponent*>
			constexpr auto OrnamentCompVisibleTagDependencies = 0x940; // Size: 80, Type: struct TMap<struct FGameplayTag, struct FCharacterTagListenerForOrnamentComp>
			constexpr auto OrnamentMontageInfo = 0x990; // Size: 24, Type: struct FOrnamentMontageInfo
			constexpr auto AttributeSubComp = 0xae8; // Size: 8, Type: struct USolarAttributeSubComponent*
			constexpr auto SolarBackpackActor = 0xb28; // Size: 8, Type: struct ASolarBackpackActor*
			constexpr auto SolarBackpackComponent = 0xb30; // Size: 8, Type: struct USolarBackpackComponent*
			constexpr auto OnBackpackItemUpdate = 0xb58; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnBackpackEnergyUpdate = 0xb68; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnBackpackEquipUpdate = 0xb78; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnBatteryIdUpdate = 0xb88; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnEnergyStateUpdate = 0xb98; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnChargeInfoUpdate = 0xba8; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnConsumableNumUpdated = 0xbb8; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnMaxEnergyUpdate = 0xbc8; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnCurEnergyUpdate = 0xbd8; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnBackpackWeaponPartUpdate = 0xbe8; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto ShieldUpMatCostMap = 0xbf8; // Size: 80, Type: struct TMap<int32_t, int32_t>
			constexpr auto MaxPileMap = 0xc48; // Size: 80, Type: struct TMap<int32_t, int32_t>
			constexpr auto MaxPileArray = 0xc98; // Size: 16, Type: struct TArray<struct FReplicateMaxPileData>
			constexpr auto IdKeyItemMap = 0xca8; // Size: 80, Type: struct TMap<int32_t, struct FSolarItemData>
			constexpr auto IdKeyItemArray = 0xcf8; // Size: 16, Type: struct TArray<struct FReplicateItemData>
			constexpr auto TypeKeyItemMap = 0xd08; // Size: 80, Type: struct TMap<enum class EItemType, struct FSolarItemData>
			constexpr auto TypeKeyItemArray = 0xd58; // Size: 16, Type: struct TArray<struct FReplicateItemData>
			constexpr auto WeaponDataArray = 0xd68; // Size: 16, Type: struct TArray<struct FReplicateItemData>
			constexpr auto WeaponDataMap = 0xd78; // Size: 80, Type: struct TMap<int32_t, struct FSolarItemData>
			constexpr auto WeaponPartsArray = 0xe18; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto IgnoreScopeSlots = 0xe30; // Size: 16, Type: struct TArray<char>
			constexpr auto EnergyState = 0xe40; // Size: 1, Type: char
			constexpr auto MaxEnergyValue = 0xe44; // Size: 4, Type: float
			constexpr auto CurrEnergyValue = 0xe48; // Size: 4, Type: float
			constexpr auto MaxExtraEnergyValue = 0xe4c; // Size: 4, Type: float
			constexpr auto CurrExtraEnergyValue = 0xe50; // Size: 4, Type: float
			constexpr auto EnergyModuleID = 0xe54; // Size: 4, Type: int32_t
			constexpr auto AddedEnergyMax = 0xe58; // Size: 4, Type: float
			constexpr auto ExtraEnergyModuleID = 0xe5c; // Size: 4, Type: int32_t
			constexpr auto AddedExtraEnergyMax = 0xe60; // Size: 4, Type: float
			constexpr auto VJetPackModuleID = 0xe64; // Size: 4, Type: int32_t
			constexpr auto HJetPackModuleID = 0xe68; // Size: 4, Type: int32_t
			constexpr auto bSettingEnergyCostEnabled = 0xe6d; // Size: 1, Type: bool
			constexpr auto DayLightID = 0xe70; // Size: 4, Type: int32_t
			constexpr auto SolarChargeRatio = 0xe74; // Size: 4, Type: float
			constexpr auto bReviveItemCleared = 0xe78; // Size: 1, Type: bool
			constexpr auto JetPropellingInfo = 0xe7c; // Size: 12, Type: struct FBackpackJetPrepelInfo
			constexpr auto BackpackPropellingMode = 0xe88; // Size: 1, Type: enum class EBackpackPropellingMode
			constexpr auto InputVector = 0xe8c; // Size: 8, Type: struct FVector2D
			constexpr auto InputActionContext = 0xea0; // Size: 8, Type: struct USolarInputActionContext*
			constexpr auto IdleTurnType = 0xea8; // Size: 1, Type: enum class EIdleTurnType
			constexpr auto CharacterLookAt = 0xeb0; // Size: 12, Type: struct FRotator
			constexpr auto CharacterOperationEvt = 0xee0; // Size: 16, Type: struct FCharacterOperationEvent
			constexpr auto OnHealthUpdateDelegate = 0xf08; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto PendingRegeneration = 0xf18; // Size: 4, Type: float
			constexpr auto DiedTime = 0xf1c; // Size: 4, Type: float
			constexpr auto bIsDeathVerge = 0xf24; // Size: 1, Type: char
			constexpr auto SolarTeamRescueComponent = 0xf38; // Size: 8, Type: struct USolarTeamRescueComponent*
			constexpr auto RescuingCharater = 0xf40; // Size: 8, Type: struct TWeakObjectPtr<ASolarCharacter>
			constexpr auto RescuingUAV = 0xf48; // Size: 8, Type: struct TWeakObjectPtr<ASolarUAVRescue>
			constexpr auto CurrentRescueState = 0xf50; // Size: 1, Type: enum class ERescueState
			constexpr auto LastRescueState = 0xf51; // Size: 1, Type: enum class ERescueState
			constexpr auto RescuedCharater = 0xf80; // Size: 8, Type: struct TWeakObjectPtr<ASolarCharacter>
			constexpr auto RescuedStartTime = 0xf88; // Size: 4, Type: float
			constexpr auto RescueInjector = 0xf90; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto RescueTime = 0xfbc; // Size: 4, Type: float
			constexpr auto DeathBoxWeaponArray = 0xfc8; // Size: 16, Type: struct TArray<struct ASolarPlayerWeapon*>
			constexpr auto DeathBoxArray = 0xfd8; // Size: 16, Type: struct TArray<struct FSolarItemData>
			constexpr auto DeathBoxEnergy = 0xfe8; // Size: 4, Type: float
			constexpr auto WaterActor = 0xff0; // Size: 8, Type: struct ASolarWaterActorNew*
			constexpr auto SwimmingWaterEffect = 0xff8; // Size: 8, Type: struct UParticleSystemComponent*
			constexpr auto HeavyJumpWaterEffect = 0x1000; // Size: 8, Type: struct UParticleSystemComponent*
			constexpr auto HorizontalFlyWaterEffects = 0x1008; // Size: 16, Type: struct TArray<struct UParticleSystemComponent*>
			constexpr auto SolarItemComponent = 0x1028; // Size: 8, Type: struct USolarItemComponent*
			constexpr auto SolarPickupComponent = 0x1030; // Size: 8, Type: struct USolarPickupComponent*
			constexpr auto bIsElectricStoreOpened = 0x1038; // Size: 1, Type: bool
			constexpr auto SolarTreatmentComponent = 0x1040; // Size: 8, Type: struct USolarTreatmentComponent*
			constexpr auto CurrentTreatState = 0x1048; // Size: 1, Type: enum class ESolarTreatmentState
			constexpr auto TreatmentCount = 0x104c; // Size: 4, Type: int32_t
			constexpr auto OnShieldRecharge = 0x1058; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnShieldBreak = 0x1068; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnShowShieldHUD = 0x1078; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnShowShieldHUDItem = 0x1088; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnShieldUpFX = 0x1098; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnCurShieldValueChanged = 0x10a8; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnShieldIDChanged = 0x10b8; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnShieldValueLow = 0x10c8; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnShieldValueChanged = 0x10d8; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto CurrShieldId = 0x10ec; // Size: 4, Type: int32_t
			constexpr auto CurUniqueShieldId = 0x10f0; // Size: 4, Type: int32_t
			constexpr auto MaxShieldValue = 0x10f4; // Size: 4, Type: float
			constexpr auto NextUpgradeShieldID = 0x10f8; // Size: 4, Type: int32_t
			constexpr auto NextUpgradeShieldEnergy = 0x10fc; // Size: 4, Type: int32_t
			constexpr auto CurrShieldValue = 0x1100; // Size: 4, Type: float
			constexpr auto CurrShieldState = 0x1104; // Size: 1, Type: enum class EShieldState
			constexpr auto CurrShieldLevel = 0x1108; // Size: 4, Type: int32_t
			constexpr auto bHasPreAdd = 0x1110; // Size: 1, Type: bool
			constexpr auto ShieldRepairOperator = 0x11b8; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto ShieldOperatorSM = 0x11c0; // Size: 8, Type: struct UStaticMesh*
			constexpr auto ShieldOperatorBigSM = 0x11c8; // Size: 8, Type: struct UStaticMesh*
			constexpr auto ShieldRepairFX = 0x11d0; // Size: 8, Type: struct UParticleSystemComponent*
			constexpr auto ShieldMultiRecoverFX = 0x11d8; // Size: 8, Type: struct UParticleSystemComponent*
			constexpr auto ShieldUpgradeBodyFX = 0x11e0; // Size: 8, Type: struct UParticleSystemComponent*
			constexpr auto ShieldUpgradeOperator = 0x11e8; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto ShieldUpgradeOperatorSM = 0x11f0; // Size: 8, Type: struct UStaticMesh*
			constexpr auto ShieldOperatorExpandTimeline = 0x11f8; // Size: 152, Type: struct FTimeline
			constexpr auto ShieldOperatorNarrowTimeline = 0x1290; // Size: 152, Type: struct FTimeline
			constexpr auto ShieldSounds = 0x1328; // Size: 80, Type: struct TMap<enum class EShieldSoundType, struct FShieldSoundData>
			constexpr auto TreasureBoxOperator = 0x1380; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto CurChargingDeathBox = 0x1388; // Size: 8, Type: struct ADeathTreasureBox*
			constexpr auto DeathBoxes = 0x1390; // Size: 16, Type: struct TArray<struct ADeathTreasureBox*>
			constexpr auto OnLocalPlayerSpectateMeStatusChanged = 0x13a8; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnHUDNickNameSet = 0x13e8; // Size: 16, Type: struct FDelegate
			constexpr auto OnHUDTeamPosSet = 0x13f8; // Size: 16, Type: struct FDelegate
			constexpr auto OnHUDDistanceSet = 0x1408; // Size: 16, Type: struct FDelegate
			constexpr auto OnHUDDistanceDisplaySet = 0x1418; // Size: 16, Type: struct FDelegate
			constexpr auto OnHUDRescueBtnActivitySet = 0x1428; // Size: 16, Type: struct FDelegate
			constexpr auto TeammateHUDComp = 0x1438; // Size: 8, Type: struct USolarTeammateHUDWidgetComponent*
			constexpr auto HUDZNomral = 0x1448; // Size: 4, Type: float
			constexpr auto HUDChangeTime = 0x144c; // Size: 4, Type: float
			constexpr auto SolarRadarComponent = 0x1468; // Size: 8, Type: struct USolarRadarComponent*
			constexpr auto ActivatedRadars = 0x1470; // Size: 288, Type: struct FRadarDataSpecContainer
			constexpr auto TargetRadarStation = 0x1590; // Size: 8, Type: struct TWeakObjectPtr<ASolarRadarStation>
			constexpr auto TargetElectricShop = 0x1598; // Size: 8, Type: struct TWeakObjectPtr<ASolarElectricShop>
			constexpr auto StatisticsTimerHandle = 0x15b0; // Size: 8, Type: struct FTimerHandle
			constexpr auto CachedInstigatorCharacter = 0x1628; // Size: 8, Type: struct ASolarCharacter*
			constexpr auto ArmorReduceValue = 0x1644; // Size: 4, Type: float
			constexpr auto HeadHitValue = 0x1648; // Size: 4, Type: float
			constexpr auto OnTakeDamageDelegate = 0x1650; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto InstigatorCharacterWeaponItemID = 0x1674; // Size: 4, Type: int32_t
			constexpr auto CriticalHits = 0x1678; // Size: 16, Type: struct TArray<struct FCriticalHitInfo>
			constexpr auto WorldMarkComponent = 0x16f0; // Size: 8, Type: struct UWorldMarkComponent*
			constexpr auto IMChatObj = 0x16f8; // Size: 8, Type: struct UIMChatObject*
			constexpr auto AIActorCapacity = 0x1700; // Size: 4, Type: int32_t
			constexpr auto StandJogSpeed = 0x17b0; // Size: 4, Type: float
			constexpr auto StandRunSpeed = 0x17b4; // Size: 4, Type: float
			constexpr auto StandSprintSpeed = 0x17b8; // Size: 4, Type: float
			constexpr auto CrouchJogSpeed = 0x17bc; // Size: 4, Type: float
			constexpr auto CrouchRunSpeed = 0x17c0; // Size: 4, Type: float
			constexpr auto CrouchSprintSpeed = 0x17c4; // Size: 4, Type: float
			constexpr auto OnJogSetClient = 0x17d0; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto bIsSprintingMove = 0x17e0; // Size: 1, Type: bool
			constexpr auto CachedSolarCharacterMovement = 0x1838; // Size: 8, Type: struct USolarCharacterMovementComponent*
			constexpr auto bIsJog = 0x1840; // Size: 1, Type: char
			constexpr auto MoveSpeedReduceBonusInHipFire = 0x1844; // Size: 4, Type: float
			constexpr auto MoveSpeedReduceBonusInAdsHipFire = 0x1848; // Size: 4, Type: float
			constexpr auto CurrentCustomJumpType = 0x185c; // Size: 1, Type: enum class ECustomJumpType
			constexpr auto CurrentJetFlyType = 0x185f; // Size: 1, Type: enum class EJetFlyType
			constexpr auto bNewJetFlyCheckFlag = 0x1860; // Size: 1, Type: char
			constexpr auto CruiseStartAnim = 0x18a8; // Size: 8, Type: struct UAnimSequence*
			constexpr auto CruiseLoopAnim = 0x18b0; // Size: 8, Type: struct UAnimSequence*
			constexpr auto CruiseEndAnim = 0x18b8; // Size: 8, Type: struct UAnimSequence*
			constexpr auto PrepareToParachuteStartTime = 0x18c0; // Size: 4, Type: float
			constexpr auto PrepareToParachuteDuration = 0x18c4; // Size: 4, Type: float
			constexpr auto PrepareToParachuteLocation = 0x18c8; // Size: 12, Type: struct FVector
			constexpr auto AgreedParachuteLocation = 0x18d4; // Size: 12, Type: struct FVector
			constexpr auto CapsuleID = 0x18f8; // Size: 4, Type: int32_t
			constexpr auto bEnableCruising = 0x18fc; // Size: 1, Type: bool
			constexpr auto BoardedRoot = 0x1900; // Size: 8, Type: struct ASolarCapsuleRoot*
			constexpr auto CruiseState = 0x1908; // Size: 1, Type: enum class ECruiseState
			constexpr auto ForceParachuteCountDown = 0x190c; // Size: 4, Type: int32_t
			constexpr auto CruiseComponentPrivate = 0x1910; // Size: 8, Type: struct UCharacterCruiseComponent*
			constexpr auto OnSkydiveTraced = 0x1920; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto HeightFogActor = 0x1930; // Size: 8, Type: struct AExponentialHeightFog*
			constexpr auto SkydiveFlyingEffects = 0x1938; // Size: 16, Type: struct TArray<struct UParticleSystemComponent*>
			constexpr auto SkydiveLandingEffects = 0x1948; // Size: 16, Type: struct TArray<struct UParticleSystemComponent*>
			constexpr auto SkydiveWholeLifetimeEffects = 0x1958; // Size: 16, Type: struct TArray<struct UParticleSystemComponent*>
			constexpr auto CurrentSkydiveStage = 0x1968; // Size: 1, Type: enum class ESkydiveStage
			constexpr auto OnSkydivingStageChangedDelegate = 0x1970; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto FollowedLeaderMovementComponent = 0x19a0; // Size: 8, Type: struct UActorComponent*
			constexpr auto WeaponSystemComponent = 0x19d8; // Size: 8, Type: struct UWeaponSystemPlayerBase*
			constexpr auto OnCharacterFired = 0x19e8; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto FirstPersonMesh = 0x1a10; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto TempSwitchWeapon = 0x1a28; // Size: 8, Type: struct ASolarPlayerWeapon*
			constexpr auto CachedCurrentWeapon = 0x1a30; // Size: 8, Type: struct ASolarPlayerWeapon*
			constexpr auto WeaponSystemVehicle = 0x1b00; // Size: 8, Type: struct UWeaponSystemVehicleComponent*
			constexpr auto BoardedVehicleInfo = 0x1b20; // Size: 16, Type: struct FBoardedVehicleInfo
			constexpr auto bOutVehicleShot = 0x1b30; // Size: 1, Type: bool
			constexpr auto VehicleRepairToolMesh = 0x1bf8; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto OnCharacterActivateEMP = 0x1c18; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnCharacterSwitchEMPEffect = 0x1c28; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto bActiveEMP = 0x1c38; // Size: 1, Type: bool
			constexpr auto bActiveInfiniteAmmo = 0x1c39; // Size: 1, Type: bool
			constexpr auto bNoticedCantCharge = 0x1c3a; // Size: 1, Type: bool
			constexpr auto CurrentSkillAnimType = 0x1c3b; // Size: 1, Type: enum class ESkillAnimType
			constexpr auto CurrentSkillAnimRightHandType = 0x1c3c; // Size: 1, Type: enum class ESkillAnimRightHandType
			constexpr auto MassInvWarningIconComponent = 0x1c40; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto ScoutEnemyObj = 0x1c80; // Size: 8, Type: struct UScoutEnemyObject*
			constexpr auto CachedDuckRollingMeshComponent = 0x1c88; // Size: 8, Type: struct UDuckRollingMeshComponent*
			constexpr auto WallRunSurfaceAngle = 0x1d08; // Size: 1, Type: char
			constexpr auto WallRunState = 0x1d09; // Size: 1, Type: enum class EWallRunState
			constexpr auto LeadDanceID = 0x1d0c; // Size: 4, Type: int32_t
			constexpr auto DebugStringBotAIInfo = 0x1db0; // Size: 16, Type: struct FString
			constexpr auto DebugStringToDrawGASServer = 0x1dc0; // Size: 16, Type: struct FString
			constexpr auto DebugStringDSTransferLog = 0x1dd0; // Size: 16, Type: struct FString
			constexpr auto RoleAbilityCharacterID = 0x1de0; // Size: 4, Type: int32_t
			constexpr auto RoleAbilityBoundPlayerLevels = 0x1de8; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto RoleAbilitySpecHandles = 0x1df8; // Size: 16, Type: struct TArray<struct FGameplayAbilitySpecHandle>
			constexpr auto RoleAbilityStartCDServerTime = 0x1e08; // Size: 16, Type: struct TArray<float>
			constexpr auto BattleUpgradeEffectCurrentLevel = 0x1e58; // Size: 4, Type: int32_t
			constexpr auto BattleUpgradeEffects = 0x1e60; // Size: 288, Type: struct FBattleUpgradeEffectContainer
			constexpr auto PermanentRescueUAV = 0x2000; // Size: 8, Type: struct TWeakObjectPtr<ASolarUAVRescue>
			constexpr auto AvailableSkywardDiveLaunchers = 0x2028; // Size: 80, Type: struct TMap<struct ASkywardDiveLauncher*, bool>
	}
} 
