namespace offsets
{
	namespace ASolarUAVRescue
	{
			constexpr auto NewState = 0x479; // Size: 1, Type: enum class EUAVRescueState
			constexpr auto SuspendAnim_Active_NotWork = 0x480; // Size: 8, Type: struct UAnimationAsset*
			constexpr auto SuspendAnim_Active_Work = 0x488; // Size: 8, Type: struct UAnimationAsset*
			constexpr auto SuspendAnim_Deactive = 0x490; // Size: 8, Type: struct UAnimationAsset*
			constexpr auto ActiveAnim = 0x498; // Size: 8, Type: struct UAnimationAsset*
			constexpr auto DeactiveAnim = 0x4a0; // Size: 8, Type: struct UAnimationAsset*
			constexpr auto BeginWorkAnim = 0x4a8; // Size: 8, Type: struct UAnimationAsset*
			constexpr auto EndWorkAnim = 0x4b0; // Size: 8, Type: struct UAnimationAsset*
			constexpr auto ExplodeAnim = 0x4b8; // Size: 8, Type: struct UAnimationAsset*
			constexpr auto ActiveEffect = 0x4c0; // Size: 8, Type: struct UParticleSystem*
			constexpr auto AppearBeginEffect = 0x4c8; // Size: 8, Type: struct UParticleSystem*
			constexpr auto AppearBeginEffectSocket = 0x4d0; // Size: 8, Type: struct FName
			constexpr auto JetEffect = 0x4d8; // Size: 8, Type: struct UParticleSystem*
			constexpr auto JetEffectSocket = 0x4e0; // Size: 8, Type: struct FName
			constexpr auto JetEffectTrans = 0x4f0; // Size: 48, Type: struct FTransform
			constexpr auto ActiveLoopEffect = 0x520; // Size: 8, Type: struct UParticleSystem*
			constexpr auto ChaActiveEffect = 0x528; // Size: 8, Type: struct UParticleSystem*
			constexpr auto ExplodeEffect = 0x530; // Size: 8, Type: struct UParticleSystem*
			constexpr auto DeathVergeEffect = 0x538; // Size: 8, Type: struct UParticleSystem*
			constexpr auto ChaActiveEffectSocket = 0x540; // Size: 8, Type: struct FName
			constexpr auto AppearEffectLength = 0x548; // Size: 4, Type: float
			constexpr auto MatAppearing = 0x550; // Size: 8, Type: struct UMaterialInstance*
			constexpr auto MatAppearingData = 0x558; // Size: 16, Type: struct TArray<struct FMatAppearingData>
			constexpr auto MatAppearEndBody = 0x568; // Size: 8, Type: struct UMaterialInstance*
			constexpr auto MatAppearEndEye = 0x570; // Size: 8, Type: struct UMaterialInstance*
			constexpr auto BeginSound = 0x578; // Size: 16, Type: struct FString
			constexpr auto EndSound = 0x588; // Size: 16, Type: struct FString
			constexpr auto ActiveChaSound = 0x598; // Size: 16, Type: struct FString
			constexpr auto ActiveAnimSound = 0x5a8; // Size: 16, Type: struct FString
			constexpr auto BeginActiveLoopSound = 0x5b8; // Size: 16, Type: struct FString
			constexpr auto EndActiveLoopSound = 0x5c8; // Size: 16, Type: struct FString
			constexpr auto DeactiveAnimSound = 0x5d8; // Size: 16, Type: struct FString
			constexpr auto ExplodeSound = 0x5e8; // Size: 16, Type: struct FString
			constexpr auto BeginDeathVergeLoopSound = 0x5f8; // Size: 16, Type: struct FString
			constexpr auto EndDeathVergeLoopSound = 0x608; // Size: 16, Type: struct FString
			constexpr auto ChaSpeedThreshold = 0x618; // Size: 4, Type: float
			constexpr auto RotateSpeed = 0x61c; // Size: 4, Type: float
			constexpr auto YawOffset = 0x620; // Size: 4, Type: float
			constexpr auto ActivatingScaleCurve = 0x628; // Size: 8, Type: struct UCurveFloat*
			constexpr auto DeactivatingScaleCurve = 0x630; // Size: 8, Type: struct UCurveFloat*
			constexpr auto TargetSpeedByDistance = 0x638; // Size: 8, Type: struct UCurveFloat*
			constexpr auto Acceleration = 0x640; // Size: 4, Type: float
			constexpr auto MaxDistance = 0x644; // Size: 4, Type: float
			constexpr auto DefaultLocationOffset = 0x654; // Size: 12, Type: struct FVector
			constexpr auto TargetLocationOffsetSpeed = 0x660; // Size: 4, Type: float
			constexpr auto ActiveDuration = 0x688; // Size: 4, Type: float
			constexpr auto ActiveEffectLength = 0x68c; // Size: 4, Type: float
			constexpr auto DeathVergeHealthThreshold = 0x690; // Size: 4, Type: float
			constexpr auto UAVIcon = 0x698; // Size: 24, Type: struct FSoftObjectPath
			constexpr auto DeathVergeEffectHandle = 0x6c0; // Size: 8, Type: struct UParticleSystemComponent*
			constexpr auto ActiveLoopEffectHandle = 0x6c8; // Size: 8, Type: struct UParticleSystemComponent*
			constexpr auto bFollowCharacter = 0x6d0; // Size: 1, Type: bool
			constexpr auto bAppearEnd = 0x6d3; // Size: 1, Type: bool
			constexpr auto bActive = 0x6f0; // Size: 1, Type: bool
			constexpr auto bPermanent = 0x6f1; // Size: 1, Type: bool
			constexpr auto bExplodeEffect = 0x6f2; // Size: 1, Type: bool
			constexpr auto HealTickInterval = 0x718; // Size: 4, Type: float
			constexpr auto HealHealthAmount = 0x71c; // Size: 4, Type: float
			constexpr auto HealShieldAmount = 0x720; // Size: 4, Type: float
			constexpr auto HealLineEffect = 0x728; // Size: 8, Type: struct UParticleSystem*
			constexpr auto HealMeshSocket = 0x730; // Size: 8, Type: struct FName
			constexpr auto BeginHealSound = 0x738; // Size: 16, Type: struct FString
			constexpr auto BeginHealLoopSound = 0x748; // Size: 16, Type: struct FString
			constexpr auto EndHealSound = 0x758; // Size: 16, Type: struct FString
			constexpr auto EndHealLoopSound = 0x768; // Size: 16, Type: struct FString
			constexpr auto BeginHealHPLoopSound = 0x778; // Size: 16, Type: struct FString
			constexpr auto EndHealHPLoopSound = 0x788; // Size: 16, Type: struct FString
			constexpr auto BeginHealShieldLoopSound = 0x798; // Size: 16, Type: struct FString
			constexpr auto EndHealShieldLoopSound = 0x7a8; // Size: 16, Type: struct FString
			constexpr auto HealLineEffectHandle = 0x7b8; // Size: 8, Type: struct UParticleSystemComponent*
			constexpr auto RescueEffect = 0x7c8; // Size: 8, Type: struct UParticleSystem*
			constexpr auto RescueEffect_Enermy = 0x7d0; // Size: 8, Type: struct UParticleSystem*
			constexpr auto RescueEffectTransform = 0x7e0; // Size: 48, Type: struct FTransform
			constexpr auto RescueMeshSocket = 0x810; // Size: 8, Type: struct FName
			constexpr auto RescueTime = 0x818; // Size: 4, Type: float
			constexpr auto bCheckRescueBlock = 0x81c; // Size: 1, Type: bool
			constexpr auto CheckRescueBlockInteval = 0x820; // Size: 4, Type: float
			constexpr auto BeginRescueLoopSound = 0x828; // Size: 16, Type: struct FString
			constexpr auto EndRescueLoopSound = 0x838; // Size: 16, Type: struct FString
			constexpr auto CompleteRescueSound = 0x848; // Size: 16, Type: struct FString
			constexpr auto RescueEffectHandle = 0x858; // Size: 8, Type: struct UParticleSystemComponent*
			constexpr auto MatInstanceAppearingBody = 0x870; // Size: 8, Type: struct UMaterialInstanceDynamic*
			constexpr auto MatInstanceAppearingEye = 0x878; // Size: 8, Type: struct UMaterialInstanceDynamic*
			constexpr auto bNavigateToOwner = 0x880; // Size: 1, Type: bool
			constexpr auto RecordInterval = 0x884; // Size: 4, Type: float
			constexpr auto NavigateInterval = 0x888; // Size: 4, Type: float
			constexpr auto BeginNavigateDistance = 0x88c; // Size: 4, Type: float
			constexpr auto EndNavigateDistance = 0x890; // Size: 4, Type: float
			constexpr auto UAVHealBuffGameplayEffect = 0x8c0; // Size: 8, Type: UGameplayEffect*
			constexpr auto UAVRescueGameplayEffect = 0x8c8; // Size: 8, Type: UGameplayEffect*
	}
} 
