namespace offsets
{
	namespace ASolarVehiclePawn
	{
			constexpr auto VehicleRoot = 0x2b8; // Size: 8, Type: struct UPrimitiveComponent*
			constexpr auto VehicleMesh = 0x2c0; // Size: 8, Type: struct USkeletalMeshComponentBudgeted*
			constexpr auto VehicleID = 0x2c8; // Size: 4, Type: uint32_t
			constexpr auto bVehicleMeshAggregationTick = 0x2cc; // Size: 1, Type: bool
			constexpr auto VehicleStencilClass = 0x2d0; // Size: 40, Type: struct TSoftClassPtr<UObject>
			constexpr auto VehicleStencilNew = 0x2f8; // Size: 8, Type: struct USkeletalMeshComponentBudgeted*
			constexpr auto NetMovementComponent = 0x300; // Size: 8, Type: struct USolarNetMovementComponent*
			constexpr auto AkComponent = 0x308; // Size: 8, Type: struct UAkComponent*
			constexpr auto VehicleAbilitySystem = 0x310; // Size: 8, Type: struct USolarVehicleAbilitySystemComponent*
			constexpr auto SpringArmComponent = 0x318; // Size: 8, Type: struct USolarVehicleSpringArmComponent*
			constexpr auto CameraComponent = 0x320; // Size: 8, Type: struct USolarVehicleCameraComponent*
			constexpr auto VehicleAttributeSet = 0x328; // Size: 8, Type: struct USolarVehicleAttributeSet*
			constexpr auto BasedMovement = 0x330; // Size: 40, Type: struct FBasedMovement
			constexpr auto SeatSlots = 0x358; // Size: 16, Type: struct TArray<struct FVehicleSeatSlot>
			constexpr auto HealthUIID = 0x368; // Size: 4, Type: int32_t
			constexpr auto VehicleBrandIcon = 0x370; // Size: 40, Type: struct TSoftObjectPtr<UTexture2D>
			constexpr auto OverlapWaterRadius = 0x398; // Size: 4, Type: float
			constexpr auto OutVehicleOffset = 0x39c; // Size: 12, Type: struct FVector
			constexpr auto WaterDraftDepth = 0x3a8; // Size: 4, Type: float
			constexpr auto CarpadProtectTime = 0x3ac; // Size: 4, Type: float
			constexpr auto CarPadAccelerationMultiplier = 0x3b0; // Size: 4, Type: float
			constexpr auto DropPassengerLocations = 0x3b8; // Size: 16, Type: struct TArray<struct FVector>
			constexpr auto DropPassengerAtTop = 0x3c8; // Size: 12, Type: struct FVector
			constexpr auto BodySocketName = 0x3d4; // Size: 8, Type: struct FName
			constexpr auto DamageBoxLocation = 0x3dc; // Size: 12, Type: struct FVector
			constexpr auto DamageBoxExtent = 0x3e8; // Size: 12, Type: struct FVector
			constexpr auto PenetrationDamageBones = 0x3f8; // Size: 16, Type: struct TArray<struct FName>
			constexpr auto VehicleMaxSpeedOnUI = 0x408; // Size: 4, Type: float
			constexpr auto VehicleControlUIType = 0x40c; // Size: 1, Type: enum class EVehicleControlUIType
			constexpr auto VehicleAnimationType = 0x40d; // Size: 1, Type: enum class EVehicleAnimationType
			constexpr auto VehicleDirectionBoneForPassenger = 0x410; // Size: 8, Type: struct FName
			constexpr auto NosCameraVFX = 0x420; // Size: 144, Type: struct FVehicleVFX
			constexpr auto NOSCameraEffectAngle = 0x4b0; // Size: 4, Type: float
			constexpr auto GCCameraVFX = 0x4c0; // Size: 144, Type: struct FVehicleVFX
			constexpr auto GCCameraEffectAngle = 0x550; // Size: 4, Type: float
			constexpr auto NosVFXes = 0x558; // Size: 16, Type: struct TArray<struct FVehicleVFX>
			constexpr auto RaiseDustEffects = 0x568; // Size: 80, Type: struct TMap<enum class EPhysicalSurface, struct TSoftObjectPtr<UParticleSystem>>
			constexpr auto SpeedThresholdForCollidingDamage = 0x5b8; // Size: 4, Type: float
			constexpr auto SpeedThresholdForStandingOn = 0x5bc; // Size: 4, Type: float
			constexpr auto SpeedThresholdForGetOnVehicle = 0x5c0; // Size: 4, Type: float
			constexpr auto EnterWaterVFX[4] = 0x5c8; // Size: 160, Type: struct TSoftObjectPtr<UParticleSystem>
			constexpr auto SprayVelocity = 0x668; // Size: 4, Type: float
			constexpr auto HeavyInSpeed = 0x66c; // Size: 4, Type: float
			constexpr auto CriticalAngle = 0x670; // Size: 4, Type: float
			constexpr auto OffsetBasedVechileLoction = 0x674; // Size: 12, Type: struct FVector
			constexpr auto CollisionSparkThreshold = 0x680; // Size: 4, Type: float
			constexpr auto CollisionSparkParticle = 0x688; // Size: 40, Type: struct TSoftObjectPtr<UParticleSystem>
			constexpr auto CollisionSparkParamNowel = 0x6b0; // Size: 8, Type: struct FName
			constexpr auto CollisionSparkParamQuantity = 0x6b8; // Size: 8, Type: struct FName
			constexpr auto VehicleSpeedThresholdToPlayVFX = 0x6c0; // Size: 4, Type: float
			constexpr auto CollisionSparkCurveFromImpulseToNowel = 0x6c8; // Size: 136, Type: struct FRuntimeFloatCurve
			constexpr auto CollisionSparkCurveFromImpulseToQuantity = 0x750; // Size: 136, Type: struct FRuntimeFloatCurve
			constexpr auto SpeedParticle = 0x7e0; // Size: 144, Type: struct FVehicleVFX
			constexpr auto DriverOnVFXMeshes = 0x870; // Size: 16, Type: struct TArray<struct FVehicleVFXMesh>
			constexpr auto DriverOnVFXs = 0x880; // Size: 16, Type: struct TArray<struct FVehicleVFX>
			constexpr auto SpawnOffset = 0x890; // Size: 12, Type: struct FVector
			constexpr auto CameraDataAsset = 0x8a0; // Size: 8, Type: struct UVehicleCameraDataAsset*
			constexpr auto SpeedVibrationHeString = 0x8a8; // Size: 16, Type: struct FString
			constexpr auto SpeedVibrationCurve = 0x8b8; // Size: 136, Type: struct FRuntimeFloatCurve
			constexpr auto MinSpeedDifferenceForCollisionVibration = 0x940; // Size: 4, Type: float
			constexpr auto CollisionVibrationHeString = 0x948; // Size: 16, Type: struct FString
			constexpr auto LandingVibrationHeString = 0x958; // Size: 16, Type: struct FString
			constexpr auto LandingVibrationCurve = 0x968; // Size: 136, Type: struct FRuntimeFloatCurve
			constexpr auto MaxSpeedDecelerationRate = 0x9f0; // Size: 4, Type: float
			constexpr auto BackLampData = 0x9f8; // Size: 40, Type: struct FSolarVehicleMaterialData
			constexpr auto VehicleMaterialDataArray = 0xa20; // Size: 16, Type: struct TArray<struct FSolarVehicleMaterialData>
			constexpr auto VehicleSoundDataAsset = 0xa30; // Size: 8, Type: struct USolarVehicleSoundDataAsset*
			constexpr auto DefaultAttributes = 0xa38; // Size: 8, Type: UGameplayEffect*
			constexpr auto CanDriveEffect = 0xa40; // Size: 8, Type: UGameplayEffect*
			constexpr auto CanGetOnEffect = 0xa48; // Size: 8, Type: UGameplayEffect*
			constexpr auto UnderWaterEffect = 0xa50; // Size: 8, Type: UGameplayEffect*
			constexpr auto ExplosionAbilityClass = 0xa58; // Size: 8, Type: ASolarAbility*
			constexpr auto ExplosionDamageInfo = 0xa60; // Size: 64, Type: struct FSolarDamageInfo
			constexpr auto ExplosionVFX = 0xaa0; // Size: 144, Type: struct FVehicleVFX
			constexpr auto VehicleBrokenMesh = 0xb30; // Size: 128, Type: struct FVehicleVFXMesh
			constexpr auto VehicleDamagedVFXs[5] = 0xbb0; // Size: 720, Type: struct FVehicleVFX
			constexpr auto VehicleDamageStatusEffects[5] = 0xe80; // Size: 40, Type: UGameplayEffect*
			constexpr auto MaxLodLevelForUpdateVisual = 0xea8; // Size: 4, Type: int32_t
			constexpr auto VehicleWeakPointContainer = 0xeb0; // Size: 16, Type: struct TArray<struct FVehicleWeakPointSpec>
			constexpr auto PlatformComponent = 0xec0; // Size: 8, Type: struct UPrimitiveComponent*
			constexpr auto bCanStandOnPlatform = 0xec8; // Size: 1, Type: bool
			constexpr auto DistanceThresholdForAttachPlatform = 0xecc; // Size: 4, Type: float
			constexpr auto DegreeThresholdForAttachPlatform = 0xed0; // Size: 4, Type: float
			constexpr auto SpeedThresholdForAttachPlatform = 0xed4; // Size: 4, Type: float
			constexpr auto TimerForPenetration = 0xed8; // Size: 4, Type: float
			constexpr auto PenetrationThreshold = 0xedc; // Size: 4, Type: float
			constexpr auto CollideDamage = 0xee0; // Size: 4, Type: float
			constexpr auto CrashDamageWeight = 0xee4; // Size: 4, Type: float
			constexpr auto SelfCrashDamageRate = 0xee8; // Size: 4, Type: float
			constexpr auto PassengerDamageRatio = 0xeec; // Size: 4, Type: float
			constexpr auto MinPlayerDamageVelocity = 0xef0; // Size: 4, Type: float
			constexpr auto CollidedCharacterDmgRatio = 0xef4; // Size: 4, Type: float
			constexpr auto CollideUpBoundingRatio = 0xef8; // Size: 4, Type: float
			constexpr auto CollidePushSpeedCurve = 0xf00; // Size: 8, Type: struct UCurveFloat*
			constexpr auto CollidePushUpAngle = 0xf08; // Size: 4, Type: float
			constexpr auto CharacterProtectTime = 0xf0c; // Size: 4, Type: float
			constexpr auto CollisionLinearVelocityDampingForSimulatedProxy = 0xf10; // Size: 4, Type: float
			constexpr auto CollisionLinearVelocityDampingSetDelay = 0xf14; // Size: 4, Type: float
			constexpr auto CollisionCompensationImpulseForSimulatedProxy = 0xf18; // Size: 4, Type: float
			constexpr auto StealthHideMats = 0xf20; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto bRemoveStencil = 0xf38; // Size: 1, Type: bool
			constexpr auto IsLaunch = 0xf50; // Size: 1, Type: bool
			constexpr auto OnPlayerGetOnVehicle = 0xf70; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnPlayerGetOffVehicle = 0xf71; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OccupiedSeats = 0x1088; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto InputActionContext = 0x1098; // Size: 8, Type: struct USolarInputActionContext*
			constexpr auto ReplicatedPlayerInputVector = 0x10a4; // Size: 12, Type: struct FVector_NetQuantizeNormal
			constexpr auto RepLocation = 0x10bc; // Size: 12, Type: struct FVector_NetQuantize
			constexpr auto ActorsOnPlatform = 0x1108; // Size: 16, Type: struct TArray<struct AActor*>
			constexpr auto CachedActorHandle = 0x113c; // Size: 4, Type: struct FSpawnedActorHandle
			constexpr auto CurPlayerInputMask = 0x1140; // Size: 1, Type: char
			constexpr auto ReplicatedPlayerInputMask = 0x1141; // Size: 1, Type: char
			constexpr auto SolarNavModifierComp = 0x11b0; // Size: 8, Type: struct USolarNavModifierComponent*
			constexpr auto bDynamicAffectNavigation = 0x11b8; // Size: 1, Type: bool
			constexpr auto SkinId = 0x1208; // Size: 4, Type: int32_t
			constexpr auto ActivedAbilityCooldownArray = 0x1220; // Size: 16, Type: struct TArray<struct FAbilityCooldownTimer>
			constexpr auto bVehicleBurningStart = 0x1231; // Size: 1, Type: bool
			constexpr auto EnterWaterDuration = 0x12f8; // Size: 4, Type: float
			constexpr auto WaterLineHeight = 0x1300; // Size: 4, Type: float
			constexpr auto WaterActor = 0x1308; // Size: 8, Type: struct ASolarWaterActorNew*
			constexpr auto SpeedCameraShakeCurve = 0x1330; // Size: 8, Type: struct UCurveFloat*
			constexpr auto SpeedScreenEffectOpacityCurve = 0x1338; // Size: 8, Type: struct UCurveFloat*
			constexpr auto SpeedScreenEffectPlayRateCurve = 0x1340; // Size: 8, Type: struct UCurveFloat*
			constexpr auto MinCameraShakeSpeed = 0x1348; // Size: 4, Type: float
			constexpr auto MinScreenEffectSpeed = 0x134c; // Size: 4, Type: float
			constexpr auto VehicleSpeedCameraShake = 0x1350; // Size: 8, Type: UCameraShake*
			constexpr auto VehicleSpeedScreenEffectRowId = 0x1358; // Size: 8, Type: struct FName
	}
} 
