namespace offsets
{
	namespace UCharacterGlobalConfig
	{
			constexpr auto CharacterSpecializedComponentInfos = 0x30; // Size: 80, Type: struct TMap<int32_t, struct FCharacterSpecializedComponentInfos>
			constexpr auto HeadBoneName = 0x80; // Size: 8, Type: struct FName
			constexpr auto TeamPerspectiveCueTag_LocalPlayer = 0x88; // Size: 8, Type: struct FGameplayCueTag
			constexpr auto TeamPerspectiveCueTag_Teammate = 0x90; // Size: 8, Type: struct FGameplayCueTag
			constexpr auto TeamPerspectiveTagRequirements_Teammate = 0x98; // Size: 80, Type: struct FGameplayTagRequirements
			constexpr auto OpponentPerspectiveCueTag = 0xe8; // Size: 8, Type: struct FGameplayCueTag
			constexpr auto OpponentPerspectiveMinDistance = 0xf0; // Size: 4, Type: float
			constexpr auto OpponentPerspectiveMaxDistance = 0xf4; // Size: 4, Type: float
			constexpr auto OpponentPerspectiveLocalPlayerTagRequirements = 0xf8; // Size: 80, Type: struct FGameplayTagRequirements
			constexpr auto OpponentPerspectiveOpponentTagRequirements = 0x148; // Size: 80, Type: struct FGameplayTagRequirements
			constexpr auto OpponentPerspectiveDisableDelay = 0x198; // Size: 4, Type: float
			constexpr auto RescueInjectorPreset = 0x1a0; // Size: 80, Type: struct FInjectorMeshPreset
			constexpr auto FastReliefPassiveTextID = 0x1f0; // Size: 4, Type: int32_t
			constexpr auto RescueTextID = 0x1f4; // Size: 4, Type: int32_t
			constexpr auto HitCameraShake = 0x1f8; // Size: 8, Type: UCameraShake*
			constexpr auto CameraShakeCD = 0x200; // Size: 4, Type: float
			constexpr auto CameraFOVParameterCollection = 0x208; // Size: 8, Type: struct UMaterialParameterCollection*
			constexpr auto ChargingDoneSoundCD = 0x210; // Size: 8, Type: int64_t
			constexpr auto ExtraVJetTimesEffect = 0x218; // Size: 8, Type: UGameplayEffect*
			constexpr auto VJetChargeScaleEffect = 0x220; // Size: 8, Type: UGameplayEffect*
			constexpr auto ExtraHJetTimesEffect = 0x228; // Size: 8, Type: UGameplayEffect*
			constexpr auto HJetChargeScaleEffect = 0x230; // Size: 8, Type: UGameplayEffect*
			constexpr auto ExtraJetTimesSetterTag = 0x238; // Size: 8, Type: struct FGameplayTag
			constexpr auto JetChargeScaleSetterTag = 0x240; // Size: 8, Type: struct FGameplayTag
			constexpr auto DeathBoxId = 0x248; // Size: 4, Type: int32_t
			constexpr auto TurnSpeed = 0x24c; // Size: 4, Type: float
			constexpr auto TurnChangeSpeedThreshold = 0x250; // Size: 4, Type: float
			constexpr auto TurnAngleThreshold = 0x254; // Size: 4, Type: float
			constexpr auto SprintTolerantAngle = 0x258; // Size: 4, Type: float
			constexpr auto SkydiveFollowingTeleportTriggerDistance = 0x25c; // Size: 4, Type: float
			constexpr auto SkydiveFollowingTeleportDistance = 0x260; // Size: 4, Type: float
			constexpr auto JetLandingTriggerMinVelocity = 0x264; // Size: 4, Type: float
			constexpr auto JetLandingHeightThreshold = 0x268; // Size: 4, Type: float
			constexpr auto JetLandingVelocity = 0x26c; // Size: 4, Type: float
			constexpr auto MaxSpeedParamB = 0x270; // Size: 4, Type: float
			constexpr auto MinSpeedParamD = 0x274; // Size: 4, Type: float
			constexpr auto NetworkMaxSmoothUpdateDistanceBySpeedCurve = 0x278; // Size: 136, Type: struct FRuntimeFloatCurve
			constexpr auto NetworkNoSmoothUpdateDistanceBySpeedCurve = 0x300; // Size: 136, Type: struct FRuntimeFloatCurve
			constexpr auto NetworkSimulatedSmoothLocationTimeBySpeedCurve = 0x388; // Size: 136, Type: struct FRuntimeFloatCurve
			constexpr auto CruiseAssetSet = 0x410; // Size: 8, Type: struct UCruiseAssetSet*
			constexpr auto AirborneStartSound = 0x418; // Size: 16, Type: struct FString
			constexpr auto AirborneJumpSound = 0x428; // Size: 16, Type: struct FString
			constexpr auto SkydivingEffectClassList = 0x438; // Size: 16, Type: struct TArray<struct FSkydivingEffectPreset>
			constexpr auto LowerLimitOfSpeedForSkydivingSoundEffect = 0x448; // Size: 4, Type: float
			constexpr auto MinPitchToPlaySkydivingLandingEffect = 0x44c; // Size: 4, Type: float
			constexpr auto StartSkydiveLoopSoundGroup_Speed = 0x450; // Size: 8, Type: struct FName
			constexpr auto StopSkydiveLoopSoundGroup_Speed = 0x458; // Size: 8, Type: struct FName
			constexpr auto StopSkydiveLoopSoundGroup_Height = 0x460; // Size: 8, Type: struct FName
			constexpr auto VaultDegree = 0x468; // Size: 4, Type: float
			constexpr auto VaultHalfHeight = 0x46c; // Size: 4, Type: float
			constexpr auto DetectorProfile = 0x470; // Size: 8, Type: struct FName
			constexpr auto KneeWaterInfluencesCharacterSpeed = 0x478; // Size: 4, Type: float
			constexpr auto WaterDraftDepthWhenDeathVerge = 0x47c; // Size: 4, Type: float
			constexpr auto ShoalWaterMaxDepth = 0x480; // Size: 4, Type: float
			constexpr auto HeavyJumpWaterMinAxisVelocity = 0x484; // Size: 4, Type: float
			constexpr auto SwimmingWaterEffectPreset = 0x488; // Size: 80, Type: struct FWaterEffectPreset
			constexpr auto HeavyJumpWaterEffectPreset = 0x4d8; // Size: 80, Type: struct FWaterEffectPreset
			constexpr auto SoftJumpWaterEffectPresets = 0x528; // Size: 16, Type: struct TArray<struct FWaterEffectPreset>
			constexpr auto InWaterLocalGameplayCueTag = 0x538; // Size: 8, Type: struct FGameplayCueTag
			constexpr auto PickupCollisionProfileName = 0x540; // Size: 8, Type: struct FName
			constexpr auto PoisonRecommendToleranceTimes = 0x548; // Size: 4, Type: float
			constexpr auto TreasureBoxOperatorMeshPreset = 0x550; // Size: 80, Type: struct FTreasureBoxOperatorMeshPreset
			constexpr auto AirDropSkillTextID = 0x5a0; // Size: 4, Type: int32_t
			constexpr auto TreatFX = 0x5a8; // Size: 16, Type: struct FString
			constexpr auto TreatmentTextID = 0x5b8; // Size: 4, Type: int32_t
			constexpr auto MinHealthRatioToShowMedicineFX = 0x5bc; // Size: 4, Type: float
			constexpr auto RevivePickupFX = 0x5c0; // Size: 40, Type: struct TSoftObjectPtr<UParticleSystem>
			constexpr auto ReviveClearFX = 0x5e8; // Size: 40, Type: struct TSoftObjectPtr<UParticleSystem>
			constexpr auto ResurrectTextID = 0x610; // Size: 4, Type: int32_t
			constexpr auto ResurrectTime = 0x614; // Size: 4, Type: float
			constexpr auto ShieldUpgradeBodyLoopFXTemplate = 0x618; // Size: 16, Type: struct TArray<struct TSoftObjectPtr<UParticleSystem>>
			constexpr auto ShieldUpgradeBodyEndFXTemplate = 0x628; // Size: 16, Type: struct TArray<struct TSoftObjectPtr<UParticleSystem>>
			constexpr auto ShieldOperatorPreset = 0x640; // Size: 288, Type: struct FOperatorMeshPreset
			constexpr auto ShieldOperatorExpandCurve = 0x760; // Size: 8, Type: struct UCurveFloat*
			constexpr auto ShieldOperatorNarrowCurve = 0x768; // Size: 8, Type: struct UCurveFloat*
			constexpr auto EffectAttachBone = 0x770; // Size: 8, Type: struct FName
			constexpr auto ShieldRechargeEffect = 0x778; // Size: 16, Type: struct FString
			constexpr auto ShieldBrokenEffect = 0x788; // Size: 16, Type: struct FString
			constexpr auto HitEffectOffset = 0x798; // Size: 4, Type: float
			constexpr auto ShieldRechargeTextID = 0x79c; // Size: 4, Type: int32_t
			constexpr auto ShieldRechargePassiveTextID = 0x7a0; // Size: 4, Type: int32_t
			constexpr auto ShieldReduceScreenEffectID = 0x7a4; // Size: 8, Type: struct FName
			constexpr auto ShieldBrokenScreenEffectID = 0x7ac; // Size: 8, Type: struct FName
			constexpr auto FirstPersonMeshConfig = 0x7b8; // Size: 8, Type: struct USkeletalMeshComponentConfig*
			constexpr auto BaseGunCollisionTraceDis = 0x7c0; // Size: 4, Type: float
			constexpr auto GunCollisionTraceStartHighIdle = 0x7c8; // Size: 80, Type: struct TMap<enum class ECharacterBodyScaleType, float>
			constexpr auto GunCollisionTraceStartHighCrouch = 0x818; // Size: 80, Type: struct TMap<enum class ECharacterBodyScaleType, float>
			constexpr auto MinDistanceGun2Wall = 0x868; // Size: 4, Type: float
			constexpr auto GunCollisionXYAdjustDownSide = 0x86c; // Size: 4, Type: float
			constexpr auto GunCollisionCheckZLimit = 0x870; // Size: 4, Type: float
			constexpr auto WeaponSystemPlayerClass = 0x878; // Size: 8, Type: UWeaponSystemPlayer*
			constexpr auto WeaponSystemAIClass = 0x880; // Size: 8, Type: UWeaponSystemPlayerAI*
			constexpr auto TrackingMarkWidgetClass = 0x888; // Size: 8, Type: UMapMarkBase*
			constexpr auto WeaponAimStartOffset = 0x890; // Size: 12, Type: struct FVector
			constexpr auto AbilitiesToCancelOnPressingWeaponAction = 0x8a0; // Size: 32, Type: struct FGameplayTagContainer
			constexpr auto DefaultHitTraceLifetime = 0x8c0; // Size: 4, Type: float
			constexpr auto DefaultHitTraceWidgetScaleCurve = 0x8c8; // Size: 8, Type: struct UCurveFloat*
			constexpr auto SniperHitTraceLifetime = 0x8d0; // Size: 4, Type: float
			constexpr auto SniperHitTraceWidgetScaleCurve = 0x8d8; // Size: 8, Type: struct UCurveFloat*
			constexpr auto MeleeHitTraceLifetime = 0x8e0; // Size: 4, Type: float
			constexpr auto VehicleHitTraceLifetime = 0x8e4; // Size: 4, Type: float
			constexpr auto VehicleHitTraceWidgetScaleCurve = 0x8e8; // Size: 8, Type: struct UCurveFloat*
			constexpr auto VehicleRepairToolMeshPreset = 0x8f0; // Size: 80, Type: struct FVehicleRepairToolMeshPreset
			constexpr auto RepairWeakPointTextID = 0x940; // Size: 4, Type: int32_t
			constexpr auto VehicleStealthEffectClass = 0x948; // Size: 8, Type: UActorEffect*
			constexpr auto TeammateHUDPreset = 0x950; // Size: 32, Type: struct FTeammateHUDPreset
			constexpr auto HUDZNomral = 0x970; // Size: 4, Type: float
			constexpr auto HUDZSwim = 0x974; // Size: 4, Type: float
			constexpr auto HUDZCrouch = 0x978; // Size: 4, Type: float
			constexpr auto HUDZCrawl = 0x97c; // Size: 4, Type: float
			constexpr auto HUDChangeTime = 0x980; // Size: 4, Type: float
			constexpr auto HUDChangeSpeed = 0x984; // Size: 4, Type: float
			constexpr auto CheckHUDDistanceToCenter = 0x988; // Size: 4, Type: float
			constexpr auto HUDTranslucentValue = 0x98c; // Size: 4, Type: float
			constexpr auto HUDComponentClass = 0x990; // Size: 8, Type: USolarTeammateHUDWidgetComponent*
			constexpr auto RadarScanSoundDataAsset = 0x998; // Size: 8, Type: struct URadarScanSoundDataAsset*
			constexpr auto RadarScannedEffectID = 0x9a0; // Size: 8, Type: struct FName
			constexpr auto RadarDetectedEffectCueTag = 0x9a8; // Size: 8, Type: struct FGameplayCueTag
			constexpr auto RadarDetectedInSmokeEffectCueTag = 0x9b0; // Size: 8, Type: struct FGameplayCueTag
			constexpr auto MassInvisibilityWarningIconClass = 0x9b8; // Size: 8, Type: UStaticMeshComponent*
			constexpr auto CharacterMassInvisibilityWarningIcon = 0x9c0; // Size: 40, Type: struct TSoftObjectPtr<UTexture2D>
			constexpr auto VehicleMassInvisibilityWarningIcon = 0x9e8; // Size: 40, Type: struct TSoftObjectPtr<UTexture2D>
			constexpr auto MassInvWarningIconScale = 0xa10; // Size: 12, Type: struct FVector
			constexpr auto MassInvWarningIconOffsetDefault = 0xa1c; // Size: 12, Type: struct FVector
			constexpr auto MassInvWarningIconOffsetCrouch = 0xa28; // Size: 12, Type: struct FVector
			constexpr auto MassInvWarningIconOffsetCrawl = 0xa34; // Size: 12, Type: struct FVector
			constexpr auto MassInvWarningIconOffsetSmoothSpeed = 0xa40; // Size: 4, Type: float
			constexpr auto MassInvWarningIconOffsetForceNoSmoothDistance = 0xa44; // Size: 4, Type: float
			constexpr auto ScoutEnemyConfig = 0xa48; // Size: 8, Type: struct UScoutEnemyConfig*
			constexpr auto bEnableEMPBlockChargeNotice = 0xa50; // Size: 1, Type: bool
			constexpr auto GyroscopeConfig = 0xa58; // Size: 8, Type: struct UGyroscopeConfig*
			constexpr auto CheckInRoomInterval = 0xa60; // Size: 4, Type: float
			constexpr auto DamageLimitTime = 0xa64; // Size: 4, Type: float
			constexpr auto DamagingDuration = 0xa68; // Size: 4, Type: float
			constexpr auto DissolvedDeathFXBindingSocketName = 0xa6c; // Size: 8, Type: struct FName
			constexpr auto PersistentActorEffectClasses = 0xa78; // Size: 16, Type: struct TArray<UActorEffect*>
			constexpr auto HealthReduceScreenEffectID = 0xa88; // Size: 8, Type: struct FName
			constexpr auto HealthLowScreenEffectID = 0xa90; // Size: 8, Type: struct FName
			constexpr auto HealthLowTipThreshold = 0xa98; // Size: 4, Type: float
			constexpr auto EnterBattleEffect = 0xaa0; // Size: 8, Type: UGameplayEffect*
			constexpr auto EnterCombatEffect = 0xaa8; // Size: 8, Type: UGameplayEffect*
	}
} 
