namespace offsets
{
	namespace USkeletalMeshComponent
	{
			constexpr auto AnimBlueprintGeneratedClass = 0x790; // Size: 8, Type: UObject*
			constexpr auto AnimClass = 0x798; // Size: 8, Type: UAnimInstance*
			constexpr auto AnimScriptInstance = 0x7a0; // Size: 8, Type: struct UAnimInstance*
			constexpr auto PostProcessAnimInstance = 0x7a8; // Size: 8, Type: struct UAnimInstance*
			constexpr auto AnimationData = 0x7b0; // Size: 24, Type: struct FSingleAnimationPlayData
			constexpr auto RootBoneTranslation = 0x7d8; // Size: 12, Type: struct FVector
			constexpr auto LineCheckBoundsScale = 0x7e4; // Size: 12, Type: struct FVector
			constexpr auto LinkedInstances = 0x810; // Size: 16, Type: struct TArray<struct UAnimInstance*>
			constexpr auto CachedBoneSpaceTransforms = 0x820; // Size: 16, Type: struct TArray<struct FTransform>
			constexpr auto CachedComponentSpaceTransforms = 0x830; // Size: 16, Type: struct TArray<struct FTransform>
			constexpr auto GlobalAnimRateScale = 0x860; // Size: 4, Type: float
			constexpr auto KinematicBonesUpdateType = 0x864; // Size: 1, Type: enum class EKinematicBonesUpdateToPhysics
			constexpr auto PhysicsTransformUpdateMode = 0x865; // Size: 1, Type: enum class EPhysicsTransformUpdateMode
			constexpr auto AnimationMode = 0x867; // Size: 1, Type: enum class EAnimationMode
			constexpr auto bDisablePostProcessBlueprint = 0x869; // Size: 1, Type: char
			constexpr auto bUpdateOverlapsOnAnimationFinalize = 0x869; // Size: 1, Type: char
			constexpr auto bHasValidBodies = 0x869; // Size: 1, Type: char
			constexpr auto bBlendPhysics = 0x869; // Size: 1, Type: char
			constexpr auto bEnablePhysicsOnDedicatedServer = 0x869; // Size: 1, Type: char
			constexpr auto bUpdateJointsFromAnimation = 0x86a; // Size: 1, Type: char
			constexpr auto bDisableClothSimulation = 0x86a; // Size: 1, Type: char
			constexpr auto bDisableRigidBodyAnimNode = 0x86a; // Size: 1, Type: char
			constexpr auto bAllowAnimCurveEvaluation = 0x86a; // Size: 1, Type: char
			constexpr auto bDisableAnimCurves = 0x86a; // Size: 1, Type: char
			constexpr auto bCollideWithEnvironment = 0x86b; // Size: 1, Type: char
			constexpr auto bCollideWithAttachedChildren = 0x86b; // Size: 1, Type: char
			constexpr auto bLocalSpaceSimulation = 0x86b; // Size: 1, Type: char
			constexpr auto bResetAfterTeleport = 0x86b; // Size: 1, Type: char
			constexpr auto bDeferKinematicBoneUpdate = 0x86b; // Size: 1, Type: char
			constexpr auto bNoSkeletonUpdate = 0x86b; // Size: 1, Type: char
			constexpr auto bPauseAnims = 0x86b; // Size: 1, Type: char
			constexpr auto bUseRefPoseOnInitAnim = 0x86c; // Size: 1, Type: char
			constexpr auto bEnablePerPolyCollision = 0x86c; // Size: 1, Type: char
			constexpr auto bForceRefpose = 0x874; // Size: 1, Type: char
			constexpr auto bOnlyAllowAutonomousTickPose = 0x874; // Size: 1, Type: char
			constexpr auto bIsAutonomousTickPose = 0x874; // Size: 1, Type: char
			constexpr auto bOldForceRefPose = 0x874; // Size: 1, Type: char
			constexpr auto bShowPrePhysBones = 0x874; // Size: 1, Type: char
			constexpr auto bRequiredBonesUpToDate = 0x874; // Size: 1, Type: char
			constexpr auto bAnimTreeInitialised = 0x874; // Size: 1, Type: char
			constexpr auto bIncludeComponentLocationIntoBounds = 0x874; // Size: 1, Type: char
			constexpr auto bEnableLineCheckWithBounds = 0x875; // Size: 1, Type: char
			constexpr auto bUseBendingElements = 0x875; // Size: 1, Type: char
			constexpr auto bUseTetrahedralConstraints = 0x875; // Size: 1, Type: char
			constexpr auto bUseThinShellVolumeConstraints = 0x875; // Size: 1, Type: char
			constexpr auto bUseSelfCollisions = 0x875; // Size: 1, Type: char
			constexpr auto bUseContinuousCollisionDetection = 0x875; // Size: 1, Type: char
			constexpr auto bPropagateCurvesToSlaves = 0x875; // Size: 1, Type: char
			constexpr auto bSkipKinematicUpdateWhenInterpolating = 0x875; // Size: 1, Type: char
			constexpr auto bSkipBoundsUpdateWhenInterpolating = 0x876; // Size: 1, Type: char
			constexpr auto bNeedsQueuedAnimEventsDispatched = 0x876; // Size: 1, Type: char
			constexpr auto CachedAnimCurveUidVersion = 0x878; // Size: 2, Type: uint16_t
			constexpr auto MassMode = 0x87a; // Size: 1, Type: enum class EClothMassMode
			constexpr auto UniformMass = 0x87c; // Size: 4, Type: float
			constexpr auto TotalMass = 0x880; // Size: 4, Type: float
			constexpr auto Density = 0x884; // Size: 4, Type: float
			constexpr auto MinPerParticleMass = 0x888; // Size: 4, Type: float
			constexpr auto ClothBlendWeight = 0x88c; // Size: 4, Type: float
			constexpr auto EdgeStiffness = 0x890; // Size: 4, Type: float
			constexpr auto BendingStiffness = 0x894; // Size: 4, Type: float
			constexpr auto AreaStiffness = 0x898; // Size: 4, Type: float
			constexpr auto VolumeStiffness = 0x89c; // Size: 4, Type: float
			constexpr auto StrainLimitingStiffness = 0x8a0; // Size: 4, Type: float
			constexpr auto ShapeTargetStiffness = 0x8a4; // Size: 4, Type: float
			constexpr auto DisallowedAnimCurves = 0x8a8; // Size: 16, Type: struct TArray<struct FName>
			constexpr auto BodySetup = 0x8b8; // Size: 8, Type: struct UBodySetup*
			constexpr auto OnConstraintBroken = 0x8c8; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto ClothingSimulationFactory = 0x8d8; // Size: 8, Type: UClothingSimulationFactory*
			constexpr auto TeleportDistanceThreshold = 0x9a8; // Size: 4, Type: float
			constexpr auto TeleportRotationThreshold = 0x9ac; // Size: 4, Type: float
			constexpr auto LastPoseTickFrame = 0x9b8; // Size: 4, Type: uint32_t
			constexpr auto ClothingInteractor = 0xa10; // Size: 8, Type: struct UClothingSimulationInteractor*
			constexpr auto OnAnimInitialized = 0xae0; // Size: 16, Type: struct FMulticastInlineDelegate
	}
} 
