namespace offsets
{
	namespace USolarLeggedVehicleMovement
	{
			constexpr auto LandingSweepTraceDistance = 0x138; // Size: 4, Type: float
			constexpr auto LandedVFXHeightThreshold = 0x13c; // Size: 4, Type: float
			constexpr auto JumpLandedVFXs = 0x140; // Size: 80, Type: struct TMap<enum class EPhysicalSurface, struct FVehicleVFX>
			constexpr auto LocomotionDatas[3] = 0x190; // Size: 84, Type: struct FVehicleLocomotionData
			constexpr auto MaxControllableDegreeOffset = 0x1e4; // Size: 4, Type: float
			constexpr auto WalkableFloorAngle = 0x1e8; // Size: 4, Type: float
			constexpr auto GravityZ = 0x1ec; // Size: 4, Type: float
			constexpr auto bDelayInputForOneFrame = 0x1f0; // Size: 1, Type: bool
			constexpr auto bEnableProceduralAnimation = 0x1f1; // Size: 1, Type: bool
			constexpr auto bAdvancedProceduralAnimation = 0x1f2; // Size: 1, Type: bool
			constexpr auto StepHeight = 0x1f4; // Size: 4, Type: float
			constexpr auto StepDistanceForward = 0x1f8; // Size: 4, Type: float
			constexpr auto StepDistanceRight = 0x1fc; // Size: 4, Type: float
			constexpr auto StepSequencePercent = 0x200; // Size: 4, Type: float
			constexpr auto MinStepDuration = 0x204; // Size: 4, Type: float
			constexpr auto MinDistanceToUnplant = 0x208; // Size: 4, Type: float
			constexpr auto FixFeetTargetsAfterPercent = 0x20c; // Size: 4, Type: float
			constexpr auto FeetTipBonesRotationInterpSpeed = 0x210; // Size: 4, Type: float
			constexpr auto SpeedCurve = 0x218; // Size: 136, Type: struct FRuntimeFloatCurve
			constexpr auto HeightCurve = 0x2a0; // Size: 136, Type: struct FRuntimeFloatCurve
			constexpr auto BodyRelativeZCurve = 0x328; // Size: 136, Type: struct FRuntimeFloatCurve
			constexpr auto AdditionalBodyRelativeZ = 0x3b0; // Size: 4, Type: float
			constexpr auto BodyRelativeRotatorCurve = 0x3b8; // Size: 8, Type: struct UCurveVector*
			constexpr auto BodyTransformLerpSpeedWithoutDriver = 0x3c0; // Size: 4, Type: float
			constexpr auto TraceLength = 0x3c4; // Size: 4, Type: float
			constexpr auto DistanceCheckMultiplier = 0x3c8; // Size: 4, Type: float
			constexpr auto RadiusCheckMultiplier = 0x3cc; // Size: 4, Type: float
			constexpr auto BodyAlignTerrainBlendSpeed = 0x3d0; // Size: 4, Type: float
			constexpr auto BodyZOffsetMultiplier = 0x3d4; // Size: 4, Type: float
			constexpr auto MaxBodyZOffset = 0x3d8; // Size: 4, Type: float
			constexpr auto MinBodyZOffset = 0x3dc; // Size: 4, Type: float
			constexpr auto MinBodyAlignPitchDegree = 0x3e0; // Size: 4, Type: float
			constexpr auto MaxBodyAlignPitchDegree = 0x3e4; // Size: 4, Type: float
			constexpr auto MinBodyAlignRollDegree = 0x3e8; // Size: 4, Type: float
			constexpr auto MaxBodyAlignRollDegree = 0x3ec; // Size: 4, Type: float
			constexpr auto SkipIkTraceDurationWhenReceiveUpdateFromServer = 0x3f0; // Size: 4, Type: float
			constexpr auto bRotateOnInput = 0x3f4; // Size: 1, Type: bool
			constexpr auto MinRotateDegree = 0x3f8; // Size: 4, Type: float
			constexpr auto LerpSpeedWithinMinRotateDegree = 0x3fc; // Size: 4, Type: float
			constexpr auto DegreeForRotatePiAnimation = 0x400; // Size: 4, Type: float
			constexpr auto DegreeForRotateHalfPiAnimation = 0x404; // Size: 4, Type: float
			constexpr auto CurrentFloor = 0x408; // Size: 148, Type: struct FFindFloorResult
			constexpr auto PostPhysicsTickFunction = 0x4a0; // Size: 48, Type: struct FLeggedVehiclePostPhysicsTickFunction
			constexpr auto bAlwaysCheckFloor = 0x5a0; // Size: 1, Type: bool
			constexpr auto MaxStepHeight = 0x5a4; // Size: 4, Type: float
			constexpr auto PerchRadiusThreshold = 0x5a8; // Size: 4, Type: float
			constexpr auto PerchAdditionalHeight = 0x5ac; // Size: 4, Type: float
			constexpr auto bCanWalkOffLedges = 0x5b0; // Size: 1, Type: bool
			constexpr auto bIgnoreBaseRotation = 0x5b1; // Size: 1, Type: bool
			constexpr auto LedgeCheckThreshold = 0x5b4; // Size: 4, Type: float
			constexpr auto bJumpIgnoreInput = 0x5b8; // Size: 1, Type: bool
			constexpr auto JumpZVelocity = 0x5bc; // Size: 4, Type: float
			constexpr auto JumpXYVelocityOnInput = 0x5c0; // Size: 4, Type: float
			constexpr auto JumpFailedTagForNotice = 0x5c4; // Size: 8, Type: struct FGameplayTag
			constexpr auto JumpFailedNoticeID = 0x5cc; // Size: 4, Type: int32_t
			constexpr auto AirControl = 0x5d0; // Size: 4, Type: float
			constexpr auto AirControlBoostMultiplier = 0x5d4; // Size: 4, Type: float
			constexpr auto AirControlBoostVelocityThreshold = 0x5d8; // Size: 4, Type: float
			constexpr auto FallingLateralFriction = 0x5dc; // Size: 4, Type: float
			constexpr auto MaxJumpApexAttemptsPerSimulation = 0x5e0; // Size: 4, Type: int32_t
			constexpr auto bNotifyApex = 0x5e4; // Size: 1, Type: bool
			constexpr auto JumpOffJumpZFactor = 0x5e8; // Size: 4, Type: float
			constexpr auto MoveSpeedFactorForPiRotation = 0x5ec; // Size: 4, Type: float
			constexpr auto MoveSpeedFactorForHalfPiRotation = 0x5f0; // Size: 4, Type: float
			constexpr auto MinFootIKEffectorZ = 0x5f4; // Size: 4, Type: float
			constexpr auto MaxFootIKEffectorZ = 0x5f8; // Size: 4, Type: float
			constexpr auto FootIKDataArray = 0x600; // Size: 16, Type: struct TArray<struct FVehicleFootIKData>
			constexpr auto IKSweepTraceRadius = 0x610; // Size: 4, Type: float
			constexpr auto IKEffectorBlendSpeed = 0x614; // Size: 4, Type: float
			constexpr auto FloorAndMeshAngleForDoubleSweep = 0x618; // Size: 4, Type: float
			constexpr auto MaxBrokenWeakPointForLocomotion = 0x61c; // Size: 4, Type: int32_t
			constexpr auto RefreshBoneTransformTimerForDedicatedServer = 0x620; // Size: 4, Type: float
			constexpr auto WeakPointParticles = 0x628; // Size: 16, Type: struct TArray<struct FVehicleVFX>
			constexpr auto MaxJoyStickYaw = 0x638; // Size: 4, Type: float
			constexpr auto MinJoyStickYaw = 0x63c; // Size: 4, Type: float
			constexpr auto MaxJoyStickPitch = 0x640; // Size: 4, Type: float
			constexpr auto MinJoyStickPitch = 0x644; // Size: 4, Type: float
			constexpr auto RotationBlendSpeed = 0x648; // Size: 4, Type: float
			constexpr auto MaxFootZValueForAlignGround = 0x64c; // Size: 4, Type: float
			constexpr auto LeaningBone = 0x650; // Size: 8, Type: struct FName
			constexpr auto LeaningBoneForwardAxis = 0x658; // Size: 1, Type: enum class EAxis
			constexpr auto SpeedThresholdForLeaning = 0x65c; // Size: 4, Type: float
			constexpr auto LeaningAnimationBlendSpeed = 0x660; // Size: 4, Type: float
			constexpr auto LeaningDegree = 0x664; // Size: 4, Type: float
			constexpr auto BaseDegreeForLeaningDegree = 0x668; // Size: 4, Type: float
			constexpr auto MaxSimulationIterations = 0x66c; // Size: 4, Type: int32_t
			constexpr auto MaxSimulationTimeStep = 0x670; // Size: 4, Type: float
			constexpr auto LandingTimerForAnitCheating = 0x674; // Size: 4, Type: float
			constexpr auto EnablePhysicsCollisionTimer = 0x678; // Size: 4, Type: float
			constexpr auto VehicleMesh = 0x680; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto UpdatedCapsule = 0x688; // Size: 8, Type: struct UCapsuleComponent*
			constexpr auto VehiclePawn = 0x690; // Size: 8, Type: struct ASolarVehiclePawn*
			constexpr auto DeferredUpdatedMoveComponent = 0x698; // Size: 8, Type: struct USceneComponent*
			constexpr auto VehicleStateMachine = 0x6a0; // Size: 8, Type: struct USolarVehicleStateMachine*
	}
} 
