namespace offsets
{
	namespace USolarVehicleSoundDataAsset
	{
			constexpr auto Engine_3P = 0x30; // Size: 16, Type: struct FString
			constexpr auto Engine_3P_Enemy = 0x40; // Size: 16, Type: struct FString
			constexpr auto Engine_Down_3P = 0x50; // Size: 16, Type: struct FString
			constexpr auto Engine_Down_3P_Enemy = 0x60; // Size: 16, Type: struct FString
			constexpr auto Engine_RTPC = 0x70; // Size: 16, Type: struct FString
			constexpr auto Engine_Stop_3P = 0x80; // Size: 16, Type: struct FString
			constexpr auto Engine_Stop_3P_Enemy = 0x90; // Size: 16, Type: struct FString
			constexpr auto Engine_Input_RTPC = 0xa0; // Size: 16, Type: struct FString
			constexpr auto MaxMoveSpeed = 0xb0; // Size: 4, Type: float
			constexpr auto MoveSpeed_Acc_RTPC = 0xb8; // Size: 16, Type: struct FString
			constexpr auto Tire_3P = 0xc8; // Size: 16, Type: struct FString
			constexpr auto Tire_3P_Enemy = 0xd8; // Size: 16, Type: struct FString
			constexpr auto Tire_End_3P = 0xe8; // Size: 16, Type: struct FString
			constexpr auto Tire_End_3P_Enemy = 0xf8; // Size: 16, Type: struct FString
			constexpr auto Tire_RTPC = 0x108; // Size: 16, Type: struct FString
			constexpr auto Tire_Group = 0x118; // Size: 16, Type: struct FString
			constexpr auto Tire_States = 0x128; // Size: 80, Type: struct TMap<enum class EPhysicalSurface, struct FString>
			constexpr auto bUseEngineRpm = 0x178; // Size: 1, Type: bool
			constexpr auto Vehicle_Collision_3P = 0x180; // Size: 16, Type: struct FString
			constexpr auto Vehicle_Collision_3P_Enemy = 0x190; // Size: 16, Type: struct FString
			constexpr auto Vehicle_Collision_RTPC = 0x1a0; // Size: 16, Type: struct FString
			constexpr auto Play_Booster_3P = 0x1b0; // Size: 16, Type: struct FString
			constexpr auto Play_Booster_3P_Enemy = 0x1c0; // Size: 16, Type: struct FString
			constexpr auto Stop_Booster_3P = 0x1d0; // Size: 16, Type: struct FString
			constexpr auto Stop_Booster_3P_Enemy = 0x1e0; // Size: 16, Type: struct FString
			constexpr auto Vehicle_Speedboard_1P = 0x1f0; // Size: 16, Type: struct FString
			constexpr auto Vehicle_Speedboard_3P = 0x200; // Size: 16, Type: struct FString
			constexpr auto Vehicle_Speedboard_3P_Enemy = 0x210; // Size: 16, Type: struct FString
			constexpr auto Vehicle_Eject_1P = 0x220; // Size: 16, Type: struct FString
			constexpr auto Vehicle_Eject_3P = 0x230; // Size: 16, Type: struct FString
			constexpr auto Vehicle_Eject_3P_Enemy = 0x240; // Size: 16, Type: struct FString
			constexpr auto Play_Vehicle_Destroyed = 0x250; // Size: 16, Type: struct FString
			constexpr auto Weakpoint_Broken_3P = 0x260; // Size: 16, Type: struct FString
			constexpr auto Weakpoint_Broken_3P_Enemy = 0x270; // Size: 16, Type: struct FString
			constexpr auto Weakpoint_Fixed_3P = 0x280; // Size: 16, Type: struct FString
			constexpr auto Weakpoint_Fixed_3P_Enemy = 0x290; // Size: 16, Type: struct FString
			constexpr auto Engine_Start_3P = 0x2a0; // Size: 16, Type: struct FString
			constexpr auto Engine_Start_3P_Enemy = 0x2b0; // Size: 16, Type: struct FString
			constexpr auto Braking_Loop_RTPC = 0x2c0; // Size: 16, Type: struct FString
			constexpr auto Play_Braking_Loop_3P = 0x2d0; // Size: 16, Type: struct FString
			constexpr auto Play_Braking_Loop_3P_Enemy = 0x2e0; // Size: 16, Type: struct FString
			constexpr auto Stop_Braking_Loop_3P = 0x2f0; // Size: 16, Type: struct FString
			constexpr auto Stop_Braking_Loop_3P_Enemy = 0x300; // Size: 16, Type: struct FString
			constexpr auto BrakingLoopSoundDegree = 0x310; // Size: 4, Type: float
			constexpr auto BrakingLoopSoundSpeed = 0x314; // Size: 4, Type: float
			constexpr auto Play_Reverse_Loop = 0x318; // Size: 16, Type: struct FString
			constexpr auto Stop_Reverse_Loop = 0x328; // Size: 16, Type: struct FString
			constexpr auto Drift_RTPC = 0x338; // Size: 16, Type: struct FString
			constexpr auto Drift_Start = 0x348; // Size: 16, Type: struct FString
			constexpr auto Drift_Stop = 0x358; // Size: 16, Type: struct FString
			constexpr auto SpeedDifferenceInKmThresholdForHitSound = 0x368; // Size: 1, Type: char
			constexpr auto Play_SelfHealing_3P = 0x370; // Size: 16, Type: struct FString
			constexpr auto Stop_SelfHealing_3P = 0x380; // Size: 16, Type: struct FString
			constexpr auto Play_vehicle_crash_ground_3P = 0x390; // Size: 16, Type: struct FString
			constexpr auto Play_vehicle_crash_ground_3P_enemy = 0x3a0; // Size: 16, Type: struct FString
			constexpr auto Vehicle_Crash_Ground_RTPC = 0x3b0; // Size: 16, Type: struct FString
			constexpr auto VehicleCrashGroundRtpcMultiplier = 0x3c0; // Size: 4, Type: float
			constexpr auto Play_vehicle_crash_water_3P = 0x3c8; // Size: 16, Type: struct FString
			constexpr auto Play_vehicle_crash_water_3P_enemy = 0x3d8; // Size: 16, Type: struct FString
			constexpr auto Play_vehicle_fixing_weakpoint_3P = 0x3e8; // Size: 16, Type: struct FString
			constexpr auto Stop_vehicle_fixing_weakpoint_3P = 0x3f8; // Size: 16, Type: struct FString
			constexpr auto Play_VehicleWholdShieldBegin_Start_1P = 0x408; // Size: 16, Type: struct FString
			constexpr auto Play_VehicleWholdShieldBegin_Loop_1P = 0x418; // Size: 16, Type: struct FString
			constexpr auto Stop_VehicleWholdShieldBegin_Start_3P = 0x428; // Size: 16, Type: struct FString
			constexpr auto Stop_VehicleWholdShieldBegin_Loop_3P = 0x438; // Size: 16, Type: struct FString
			constexpr auto Play_VehicleWholdShieldEnd_Start_1P = 0x448; // Size: 16, Type: struct FString
			constexpr auto Play_VehicleWholdShieldEnd_Loop_1P = 0x458; // Size: 16, Type: struct FString
			constexpr auto Stop_VehicleWholdShieldEnd_Start_3P = 0x468; // Size: 16, Type: struct FString
			constexpr auto Stop_VehicleWholdShieldEnd_Loop_3P = 0x478; // Size: 16, Type: struct FString
			constexpr auto Play_HitVehicleWholdShield_1P = 0x488; // Size: 16, Type: struct FString
			constexpr auto Play_HitVehicleWholdShield_3P = 0x498; // Size: 16, Type: struct FString
			constexpr auto HoverJumpOnActive1P = 0x4a8; // Size: 16, Type: struct FString
			constexpr auto HoverJumpOnActive3P = 0x4b8; // Size: 16, Type: struct FString
			constexpr auto HoverJumpWhileActive1P = 0x4c8; // Size: 16, Type: struct FString
			constexpr auto HoverJumpWhileActive3P = 0x4d8; // Size: 16, Type: struct FString
			constexpr auto HoverJumpOnRemove1P = 0x4e8; // Size: 16, Type: struct FString
			constexpr auto HoverJumpOnRemove3P = 0x4f8; // Size: 16, Type: struct FString
			constexpr auto Play_VehicleTrumpet_1P = 0x508; // Size: 16, Type: struct FString
			constexpr auto Play_VehicleTrumpet_3P = 0x518; // Size: 16, Type: struct FString
			constexpr auto Stop_VehicleTrumpet_1P = 0x528; // Size: 16, Type: struct FString
			constexpr auto Stop_VehicleTrumpet_3P = 0x538; // Size: 16, Type: struct FString
			constexpr auto Play_vehicle_common_braking_loop_3P = 0x548; // Size: 16, Type: struct FString
			constexpr auto Play_vehicle_common_braking_loop_3P_enemy = 0x558; // Size: 16, Type: struct FString
			constexpr auto Stop_vehicle_common_braking_loop_3P = 0x568; // Size: 16, Type: struct FString
			constexpr auto Stop_vehicle_common_braking_loop_3P_enemy = 0x578; // Size: 16, Type: struct FString
			constexpr auto Play_Vehicle_UpShift_3P = 0x588; // Size: 16, Type: struct FString
			constexpr auto Play_Vehicle_UpShift_3P_Enemy = 0x598; // Size: 16, Type: struct FString
			constexpr auto Play_Vehicle_DownShift_3P = 0x5a8; // Size: 16, Type: struct FString
			constexpr auto Play_Vehicle_DownShift_3P_Enemy = 0x5b8; // Size: 16, Type: struct FString
			constexpr auto Play_IronMan_Laser_Hit = 0x5c8; // Size: 16, Type: struct FString
			constexpr auto FootPlant = 0x5d8; // Size: 16, Type: struct FString
			constexpr auto Landing_3P = 0x5e8; // Size: 16, Type: struct FString
			constexpr auto Landing_3P_Enemy = 0x5f8; // Size: 16, Type: struct FString
	}
} 
