namespace offsets
{
	namespace UUI_Lobby_RoomInvite_Popup_C
	{
			constexpr auto UberGraphFrame = 0x348; // Size: 8, Type: struct FPointerToUberGraphFrame
			constexpr auto Anim_Loop = 0x350; // Size: 8, Type: struct UWidgetAnimation*
			constexpr auto Anim_Exit = 0x358; // Size: 8, Type: struct UWidgetAnimation*
			constexpr auto Anim_Enter = 0x360; // Size: 8, Type: struct UWidgetAnimation*
			constexpr auto Btn_Join_Common = 0x368; // Size: 8, Type: struct USolarButton*
			constexpr auto Btn_Join_League = 0x370; // Size: 8, Type: struct USolarButton*
			constexpr auto Btn_Joining = 0x378; // Size: 8, Type: struct USolarButton*
			constexpr auto Btn_Player = 0x380; // Size: 8, Type: struct UButton*
			constexpr auto Btn_Player_2 = 0x388; // Size: 8, Type: struct UButton*
			constexpr auto Btn_Watch = 0x390; // Size: 8, Type: struct USolarButton*
			constexpr auto HorizentalBox_Match = 0x398; // Size: 8, Type: struct UHorizontalBox*
			constexpr auto HorizentalBox_Spectator = 0x3a0; // Size: 8, Type: struct UHorizontalBox*
			constexpr auto HorizontalBox_Join = 0x3a8; // Size: 8, Type: struct UHorizontalBox*
			constexpr auto HorizontalBox_Joining_2 = 0x3b0; // Size: 8, Type: struct UHorizontalBox*
			constexpr auto HorizontalBox_League = 0x3b8; // Size: 8, Type: struct UHorizontalBox*
			constexpr auto HorizontalBox_Player = 0x3c0; // Size: 8, Type: struct UHorizontalBox*
			constexpr auto HorizontalBox_Title_Common = 0x3c8; // Size: 8, Type: struct UHorizontalBox*
			constexpr auto HorizontalBox_Title_Common_2 = 0x3d0; // Size: 8, Type: struct UHorizontalBox*
			constexpr auto HorizontalBox_Title_League = 0x3d8; // Size: 8, Type: struct UHorizontalBox*
			constexpr auto HorizontalBox_Watch = 0x3e0; // Size: 8, Type: struct UHorizontalBox*
			constexpr auto Img_BG_Light = 0x3e8; // Size: 8, Type: struct UImage*
			constexpr auto Img_BG_Light_01 = 0x3f0; // Size: 8, Type: struct UImage*
			constexpr auto Img_Btn_Join = 0x3f8; // Size: 8, Type: struct UImage*
			constexpr auto Img_Btn_Join_2 = 0x400; // Size: 8, Type: struct UImage*
			constexpr auto Img_Btn_Joining_Close = 0x408; // Size: 8, Type: struct UImage*
			constexpr auto Img_Btn_Watch = 0x410; // Size: 8, Type: struct UImage*
			constexpr auto Img_Division = 0x418; // Size: 8, Type: struct UImage*
			constexpr auto Img_Join_Common_Light = 0x420; // Size: 8, Type: struct UImage*
			constexpr auto Img_Join_Light = 0x428; // Size: 8, Type: struct UImage*
			constexpr auto Img_League_Icon = 0x430; // Size: 8, Type: struct USolarImageURL*
			constexpr auto Img_Title_BG = 0x438; // Size: 8, Type: struct UImage*
			constexpr auto Img_Title_BG_2 = 0x440; // Size: 8, Type: struct UImage*
			constexpr auto Img_Watch_Light = 0x448; // Size: 8, Type: struct UImage*
			constexpr auto Overlay_Avatar = 0x450; // Size: 8, Type: struct UOverlay*
			constexpr auto Overlay_Avatar_2 = 0x458; // Size: 8, Type: struct UOverlay*
			constexpr auto Overlay_Cup = 0x460; // Size: 8, Type: struct UOverlay*
			constexpr auto Panel_Info_CreateRoom = 0x468; // Size: 8, Type: struct UCanvasPanel*
			constexpr auto Panel_Info_Invitation = 0x470; // Size: 8, Type: struct UCanvasPanel*
			constexpr auto Panel_Pop_Common = 0x478; // Size: 8, Type: struct UCanvasPanel*
			constexpr auto Panel_Pop_League = 0x480; // Size: 8, Type: struct UCanvasPanel*
			constexpr auto RichTxt_LvlRequired = 0x488; // Size: 8, Type: struct USolarRichTextBlock*
			constexpr auto Txt_Capacity = 0x490; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Txt_Clan_Quantity = 0x498; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Txt_GameMode = 0x4a0; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Txt_GameMode_2 = 0x4a8; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Txt_Invitation = 0x4b0; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Txt_Join = 0x4b8; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Txt_Join_Common = 0x4c0; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Txt_Joining = 0x4c8; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Txt_League_Name = 0x4d0; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Txt_Map = 0x4d8; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Txt_Map_2 = 0x4e0; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Txt_Map_3 = 0x4e8; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Txt_Mode = 0x4f0; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Txt_Number = 0x4f8; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Txt_OBCurr = 0x500; // Size: 8, Type: struct UTextBlock*
			constexpr auto Txt_OBCurr_2 = 0x508; // Size: 8, Type: struct UTextBlock*
			constexpr auto Txt_OBCurr_4 = 0x510; // Size: 8, Type: struct UTextBlock*
			constexpr auto Txt_OBTotal = 0x518; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Txt_PlayerIn = 0x520; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Txt_PlayerName = 0x528; // Size: 8, Type: struct UTextBlock*
			constexpr auto Txt_Progress_Des = 0x530; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Txt_Progress_Time = 0x538; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Txt_RoomName = 0x540; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto Txt_Watch = 0x548; // Size: 8, Type: struct USolarTextBlock*
			constexpr auto UI_Component_Close = 0x550; // Size: 8, Type: struct UUI_Component_Close_C*
			constexpr auto UI_Component_Platform = 0x558; // Size: 8, Type: struct UUI_Component_Platform_C*
			constexpr auto UI_Component_PlayerHead = 0x560; // Size: 8, Type: struct UUI_Component_PlayerHead_C*
			constexpr auto UI_Component_PlayerHead_2 = 0x568; // Size: 8, Type: struct UUI_Component_PlayerHead_C*
			constexpr auto VerticalBox_League = 0x570; // Size: 8, Type: struct UVerticalBox*
			constexpr auto Gender = 0x578; // Size: 1, Type: enum class E_Type_CreateRoom_Gender
			constexpr auto Pop_Type = 0x579; // Size: 1, Type: enum class T_Type_System_Push
			constexpr auto Btn_Type = 0x57a; // Size: 1, Type: enum class T_Type_Button
	}
} 
