// BlueprintGeneratedClass FL_NextGenCustomMode.FL_NextGenCustomMode_C
// Size: 0x28 (Inherited: 0x28)
struct UFL_NextGenCustomMode_C : UBlueprintFunctionLibrary {

	void [ A]BindOnBasicSystemReady(struct FDelegate& Event, struct UObject* __WorldContext, bool& bReady); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[ A]BindOnBasicSystemReady // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x2d656b0
	bool UseNewAiComp(struct UObject* __WorldContext); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.UseNewAiComp // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	void GetAiComp(struct UObject* __WorldContext, struct USBattleRoyaleGameModeAIComp*& AiComp); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.GetAiComp // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	void SortMap(struct TMap<struct FString, float> MapIn, bool Ascending, struct UObject* __WorldContext, struct TMap<struct FString, float>& Sorted); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.SortMap // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x2d656b0
	struct UUserWidget* [c]ShowWidget(struct UUserWidget* WidgetClass, enum class E_UI_Root Layer, struct UObject* __WorldContext); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[c]ShowWidget // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x2d656b0
	void [c]CreateWidget(struct UUserWidget* WidgetClass, enum class E_UI_Root Layer, struct UObject* __WorldContext, struct UUserWidget*& WidgetObject); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[c]CreateWidget // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x2d656b0
	void GetRandomKeyInWidget(struct TMap<int32_t, int32_t> Key-Weight, struct UObject* __WorldContext, int32_t& HitKey); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.GetRandomKeyInWidget // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x2d656b0
	void SumOfIntArray(struct TArray<int32_t>& Array, struct UObject* __WorldContext, int32_t& Sum); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.SumOfIntArray // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure|Const) // @ game+0x2d656b0
	void GetTeamPlayerCount(struct UObject* __WorldContext, int32_t& Num Mode); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.GetTeamPlayerCount // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	void [A]GetModeConfig(struct UObject* __WorldContext, struct UCGMGameplayConfig*& ModeConfig); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[A]GetModeConfig // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	void [C]SetWidgetVisibility(enum class E_BattleControlWidgets Widget, bool Visibility, struct UObject* __WorldContext); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[C]SetWidgetVisibility // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x2d656b0
	void [A]GetDSTime(struct UObject* __WorldContext, int32_t& Time); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[A]GetDSTime // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	void [A]GetBattleTime(struct UObject* __WorldContext, int32_t& Time); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[A]GetBattleTime // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	void ToBool(struct FString String, struct UObject* __WorldContext, bool& bool); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.ToBool // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	void [A]PrintLog(struct FString Prefix, struct TMap<struct FString, struct FString>& InputPin, struct UObject* __WorldContext); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[A]PrintLog // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x2d656b0
	void [A]GetCharacters(bool OnlyRealPlayers, struct UObject* __WorldContext, struct TArray<struct ASolarCharacter*>& Characters); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[A]GetCharacters // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x2d656b0
	void [A]GetTeamCountMax(struct UObject* __WorldContext, int32_t& OutValue); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[A]GetTeamCountMax // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	void [S]SetTeamCountMax(int32_t InValue, struct UObject* __WorldContext); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[S]SetTeamCountMax // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x2d656b0
	void [A]GetPlayerCountMax(struct UObject* __WorldContext, int32_t& OutValue); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[A]GetPlayerCountMax // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	void [S]SetPlayerCountMax(int32_t InValue, struct UObject* __WorldContext); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[S]SetPlayerCountMax // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x2d656b0
	void [c]FillInCanvas(struct UCanvasPanelSlot* Slot, struct UObject* __WorldContext); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[c]FillInCanvas // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x2d656b0
	void [S]UpdateTeamsCount(int32_t Change, bool Set, struct UObject* __WorldContext, int32_t& Current); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[S]UpdateTeamsCount // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x2d656b0
	void [C]RemoveAllWidgetsFromBigMapUI(enum class E_BigMapSlot Slot, struct UObject* __WorldContext, bool& Success); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[C]RemoveAllWidgetsFromBigMapUI // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x2d656b0
	void [C]InsertWidgetToBigMapUI(struct UUserWidget* Widget, enum class E_BigMapSlot Slot, bool bReplaceOldWidget, struct UObject* __WorldContext, struct UPanelSlot*& OutResultSlot, bool& Success); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[C]InsertWidgetToBigMapUI // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x2d656b0
	void [C]RemoveAllWidgetsFromBackpackUI(enum class E_BackPackSlot Slot, struct UObject* __WorldContext, bool& Success); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[C]RemoveAllWidgetsFromBackpackUI // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x2d656b0
	void [C]InsertWidgetToBackpackUI(struct UUserWidget* Widget, enum class E_BackPackSlot Slot, bool bReplaceOldWidget, struct UObject* __WorldContext, struct UPanelSlot*& OutResultSlot, bool& Success); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[C]InsertWidgetToBackpackUI // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x2d656b0
	void [s]IsTesting(struct UObject* __WorldContext, bool& Testing); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[s]IsTesting // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	void [A]GetAllRealPlayers(struct UObject* __WorldContext, struct TArray<struct ASCMPlayerState*>& RealPlayers); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[A]GetAllRealPlayers // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x2d656b0
	void [A]PrintStringArray(struct FString Prefix, struct TArray<struct FString>& Array, struct UObject* __WorldContext); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[A]PrintStringArray // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x2d656b0
	void [A]DataInt++(enum class ESCMHostType HostType, struct FString HostID, struct FString DataName, int32_t InValue, struct UObject* __WorldContext); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[A]DataInt++ // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x2d656b0
	void [A]GetRandomLocationNearby(struct FVector Center, float Radius, struct UObject* __WorldContext, struct FVector& TargetLocation1); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[A]GetRandomLocationNearby // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	void UpdatePlayerCount(int32_t Change, bool Set, struct UObject* __WorldContext, int32_t& Current); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.UpdatePlayerCount // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x2d656b0
	void BattleOver(struct UObject* __WorldContext); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.BattleOver // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x2d656b0
	void DeathReason2String(enum class ESCMDamageType DamageType, struct UObject* __WorldContext, struct FString& TraceString); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.DeathReason2String // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	void [A]GetPlayerType(struct ASCMPlayerState* Player, struct UObject* __WorldContext, enum class E_PlayerType& PlayerType); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[A]GetPlayerType // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	void [S]GetOutcomIDByChestID(int32_t Key, struct UObject* __WorldContext, int32_t& OutcomeID); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[S]GetOutcomIDByChestID // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	void Vector2DArray2String(struct TArray<struct FVector2D>& Vector, struct UObject* __WorldContext, struct FString& str); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.Vector2DArray2String // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	void VectorArray2String(struct TArray<struct FVector>& Vector, struct UObject* __WorldContext, struct FString& str); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.VectorArray2String // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	void Vector2D2String(struct FVector2D Vector, struct UObject* __WorldContext, struct FString& str); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.Vector2D2String // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	void  äΩÈÄâ(int32_t   , int32_t   , struct TArray<int32_t>&   , struct UObject* __WorldContext, int32_t& Result); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C. äΩÈÄâ // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	void [S]GetBuildPackageType(struct UObject* __WorldContext, enum class ESolarBuildConfiguration&  âì ); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[S]GetBuildPackageType // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	void [S]Number2Letter(int32_t Number, struct UObject* __WorldContext, struct FString& Letter, bool& Valid); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[S]Number2Letter // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	void Vector2String(struct FVector Vector, struct UObject* __WorldContext, struct FString& str); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.Vector2String // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	void Bool2String(bool bool, struct UObject* __WorldContext, struct FString& String); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.Bool2String // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	void  é∑Âèñ(struct FVector   , bool  ªé , struct UObject* __WorldContext, struct FVector&  ú∞ , float& Z, bool&  òØ  ); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C. é∑Âèñ // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	void ToInt(StringArray)(struct TArray<struct FString>& str, struct UObject* __WorldContext, struct TArray<int32_t>& Int); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.ToInt(StringArray) // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	void [A]GetMiniMapSize(int32_t MapId, struct UObject* __WorldContext, struct FVector2D& Size); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[A]GetMiniMapSize // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x2d656b0
	void [S]GetMapIDByName(struct FString LevelName, struct UObject* __WorldContext, int32_t& MapId); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[S]GetMapIDByName // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	struct UCGMLogicComponent* [S]GetModeMainLogic(struct UObject* __WorldContext); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[S]GetModeMainLogic // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	void [S]DeployPlayer(struct ASolarPlayerState* TargetPlayer, struct APlayerStart* PlayerStart, bool ClearPlayerItems, struct UObject* __WorldContext); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[S]DeployPlayer // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x2d656b0
	void [A]WorldLocationToMiniMap(struct FVector WorldLocation, struct UObject* __WorldContext, struct FVector2D& MiniMapPosition); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[A]WorldLocationToMiniMap // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure|Const) // @ game+0x2d656b0
	void [A]MiniMapToWorldLocation(struct FVector2D MiniMapPosition, float Z, struct UObject* __WorldContext, struct FVector& WorldLocation); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[A]MiniMapToWorldLocation // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure|Const) // @ game+0x2d656b0
	struct USolarUserWidget* [c] Create Widget And Display(struct USolarUserWidget* WidgetClass, enum class E_UI_Root DisplayLayer, struct UObject* __WorldContext); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[c] Create Widget And Display // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x2d656b0
	struct USolarMapManager* [A]GetMapManager(struct UObject* __WorldContext); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[A]GetMapManager // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	struct ASolarCharacter* [C]GetLocalCharacter(struct UObject* __WorldContext); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[C]GetLocalCharacter // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	void [s]GetWarmGameInfo(struct UObject* __WorldContext, bool& bIsWarmGame, struct FSolarTablesData_WarmGameMode& WarmGameInfo); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[s]GetWarmGameInfo // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x2d656b0
	void [S]PlayInEditor(struct UObject* __WorldContext, bool& bIsEditor); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[S]PlayInEditor // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	void [A]GetBotTemplete(struct UObject* __WorldContext, struct TMap<int32_t, int32_t>& Templete); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[A]GetBotTemplete // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	void [A]GetExcelTableReader(struct UObject* __WorldContext, struct USolarTables_TablesReader*& TablesReader); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[A]GetExcelTableReader // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	void [s] Set Global Damage Enable(bool Enabled, struct UObject* __WorldContext); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[s] Set Global Damage Enable // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x2d656b0
	void [s] Get Logic Component(struct UObject* __WorldContext, struct UCGMLogicComponent*& Logic Component); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[s] Get Logic Component // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x2d656b0
	void [C]RemoveAllWidgetsFromBattleUI(enum class E_BattleControllerSlot Slot, struct UObject* __WorldContext, bool& Success); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[C]RemoveAllWidgetsFromBattleUI // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x2d656b0
	void [C]InsertWidgetToBattleUI(struct UUserWidget* Widget, enum class E_BattleControllerSlot Slot, bool bReplaceOldWidget, struct UObject* __WorldContext, struct UPanelSlot*& OutResultSlot, bool& Success); // Function FL_NextGenCustomMode.FL_NextGenCustomMode_C.[C]InsertWidgetToBattleUI // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x2d656b0
};

